# Generated by Django 5.0.6 on 2026-08-17 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        help_text="Auto-generated: INV-YYYY-NNNN",
                        max_length=50,
                        unique=True,
                        verbose_name="invoice number",
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("question_creation", "Question Creation"),
                            ("question_review", "Question Review"),
                            ("psychometric_review", "Psychometric Review"),
                            ("training", "Training Services"),
                            ("counseling", "Counseling Services"),
                            ("channel_partner", "Channel Partner Commission"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                        verbose_name="invoice type",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="What this invoice is for", verbose_name="description"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="amount"),
                ),
                (
                    "currency",
                    models.CharField(default="INR", max_length=3, verbose_name="currency"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted (awaiting CJ Admin review)"),
                            ("approved", "Approved (payment initiated)"),
                            ("rejected", "Rejected by CJ Admin"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled by creator"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "review_comment",
                    models.TextField(blank=True, default="", verbose_name="review comment"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="reviewed at"),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True, verbose_name="paid at")),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="payment reference"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        help_text="If this invoice is for a specific task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "invoice",
                "verbose_name_plural": "invoices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("description", models.TextField(verbose_name="description")),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="quantity")),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="unit price"),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="total"),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="invoicing.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "invoice item",
                "verbose_name_plural": "invoice items",
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["creator", "status"], name="invoicing_i_creator_eed901_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["status", "created_at"], name="invoicing_i_status_bac585_idx"
            ),
        ),
    ]
