# Generated by Django 5.0.6 on 2026-07-19 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessment", "0002_assessment_assessment_type"),
        ("career_profiling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("objective", models.TextField(blank=True, verbose_name="objective")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("descriptive", "Descriptive Report"),
                            ("typological", "Typological Report"),
                            ("interpretative", "Interpretative Report"),
                        ],
                        default="descriptive",
                        max_length=20,
                        verbose_name="report type",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("general", "General Report (single assessment)"),
                            (
                                "profiling",
                                "Profiling Report (multiple assessments via profiling solution)",
                            ),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="scope",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft (being configured)"),
                            ("published", "Published (available for generation)"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "include_score_summary",
                    models.BooleanField(default=True, verbose_name="include score summary"),
                ),
                (
                    "include_section_breakdown",
                    models.BooleanField(default=True, verbose_name="include section breakdown"),
                ),
                (
                    "include_question_analysis",
                    models.BooleanField(default=False, verbose_name="include question analysis"),
                ),
                (
                    "include_charts",
                    models.BooleanField(default=True, verbose_name="include charts"),
                ),
                (
                    "include_recommendations",
                    models.BooleanField(default=False, verbose_name="include recommendations"),
                ),
                (
                    "header_text",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="header text"
                    ),
                ),
                (
                    "footer_text",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="footer text"
                    ),
                ),
                ("logo", models.TextField(blank=True, default="", null=True, verbose_name="logo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        blank=True,
                        help_text="For general reports: the assessment this report is based on.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="assessment.assessment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profiling_solution",
                    models.ForeignKey(
                        blank=True,
                        help_text="For profiling reports: the solution this report is based on.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="career_profiling.profilingsolution",
                    ),
                ),
            ],
            options={
                "verbose_name": "report",
                "verbose_name_plural": "reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("header", "Header (title + logo)"),
                            ("score_summary", "Score Summary (total + percentage)"),
                            ("section_breakdown", "Section Breakdown (per-variable scores)"),
                            ("question_analysis", "Question Analysis (per-question details)"),
                            ("chart", "Chart (bar/pie/radar)"),
                            ("narrative", "Narrative Text (descriptive/interpretative)"),
                            ("recommendation", "Recommendations"),
                            ("footer", "Footer"),
                            ("custom", "Custom Content"),
                        ],
                        default="custom",
                        max_length=20,
                        verbose_name="section type",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="title"),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="For narrative sections: the text content. For charts: JSON config.",
                        verbose_name="content",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                ("is_visible", models.BooleanField(default=True, verbose_name="visible")),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="reporting.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "report section",
                "verbose_name_plural": "report sections",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "rendered_data",
                    models.JSONField(
                        blank=True,
                        help_text="The computed report data: scores, charts, narratives, etc.",
                        null=True,
                        verbose_name="rendered data",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("generated", "Generated"), ("failed", "Failed")],
                        default="generated",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="error message"),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to="assessment.assessmentsession",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to="reporting.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "generated report",
                "verbose_name_plural": "generated reports",
                "ordering": ["-generated_at"],
                "unique_together": {("report", "session")},
            },
        ),
    ]
