# Generated by Django 5.0.6 on 2026-07-20 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0002_assessment_assessment_type"),
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="data_input_level",
            field=models.CharField(
                choices=[
                    ("level0", "Level 0 (entire assessment summary)"),
                    ("level1", "Level 1 (all L1 variables)"),
                    ("level2", "Level 2 (all L2 variables)"),
                    ("level3", "Level 3 (all L3 variables)"),
                    ("level4", "Level 4 (all L4 variables)"),
                    ("question", "Question Level (per-question scores)"),
                ],
                default="level1",
                help_text="Which level of summary scores to use in the report.",
                max_length=20,
                verbose_name="data input level",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="include_fmi",
            field=models.BooleanField(default=False, verbose_name="include FMI report"),
        ),
        migrations.AddField(
            model_name="report",
            name="include_pmi",
            field=models.BooleanField(default=False, verbose_name="include PMI report"),
        ),
        migrations.AddField(
            model_name="report",
            name="include_raw_summary",
            field=models.BooleanField(default=True, verbose_name="include raw summary"),
        ),
        migrations.AddField(
            model_name="report",
            name="include_vmi",
            field=models.BooleanField(default=False, verbose_name="include VMI report"),
        ),
        migrations.AddField(
            model_name="report",
            name="stat_conversion",
            field=models.CharField(
                choices=[
                    ("percentage", "Percentage Score"),
                    ("percentile", "Percentile Score"),
                    ("sten", "STEN Score"),
                    ("stenine", "STENINE Score"),
                ],
                default="percentage",
                help_text="How raw scores are converted for display.",
                max_length=20,
                verbose_name="statistical conversion",
            ),
        ),
        migrations.AddField(
            model_name="reportsection",
            name="table_graph_config",
            field=models.JSONField(
                blank=True,
                help_text="JSON with table_heads or graph_legends configuration.",
                null=True,
                verbose_name="table/graph configuration",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("descriptive", "Descriptive Report"),
                    ("typological", "Typological Report"),
                    ("interpretative", "Interpretative Report"),
                    ("group", "Group Report"),
                ],
                default="descriptive",
                max_length=20,
                verbose_name="report type",
            ),
        ),
        migrations.AlterField(
            model_name="reportsection",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("header", "Header (title + logo)"),
                    ("score_summary", "Score Summary (total + percentage)"),
                    ("section_breakdown", "Section Breakdown (per-variable scores)"),
                    ("question_analysis", "Question Analysis (per-question details)"),
                    ("chart", "Chart (bar/pie/radar)"),
                    ("narrative", "Narrative Text (descriptive/interpretative)"),
                    ("cutoff_table", "Cutoff Table (descriptive)"),
                    ("type_profile", "Type Profile (typological)"),
                    ("band_table", "Band Table (interpretative)"),
                    ("fmi_report", "FMI Report (profiling)"),
                    ("pmi_report", "PMI Report (profiling)"),
                    ("vmi_report", "VMI Report (profiling)"),
                    ("recommendation", "Recommendations"),
                    ("footer", "Footer"),
                    ("custom", "Custom Content"),
                ],
                default="custom",
                max_length=20,
                verbose_name="section type",
            ),
        ),
        migrations.CreateModel(
            name="ReportBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("band_number", models.PositiveIntegerField(default=1, verbose_name="band number")),
                ("range_min", models.FloatField(default=0, verbose_name="range min")),
                ("range_max", models.FloatField(default=100, verbose_name="range max")),
                (
                    "band_label",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="band label"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="description"),
                ),
                (
                    "colour_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hex colour, e.g., #FF0000",
                        max_length=20,
                        verbose_name="colour code",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bands",
                        to="reporting.report",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        help_text="The variable (section) this band applies to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_bands",
                        to="assessment.assessmentsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "report band",
                "verbose_name_plural": "report bands",
                "ordering": ["section__level", "section__order", "band_number"],
            },
        ),
        migrations.CreateModel(
            name="PolarVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "opposite_name",
                    models.CharField(
                        help_text="Name of the opposite variable (e.g., 'Introversion' if primary is 'Extroversion')",
                        max_length=255,
                        verbose_name="opposite variable name",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polar_variables",
                        to="reporting.report",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        help_text="The primary variable.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polar_variables",
                        to="assessment.assessmentsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "polar variable",
                "verbose_name_plural": "polar variables",
                "ordering": ["section__level", "section__order"],
                "unique_together": {("report", "section")},
            },
        ),
        migrations.CreateModel(
            name="ReportCutoff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "cutoff_score",
                    models.FloatField(
                        help_text="Threshold value (in the selected conversion type)",
                        verbose_name="cutoff score",
                    ),
                ),
                (
                    "cutoff_label",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="cutoff label"
                    ),
                ),
                (
                    "above_description",
                    models.TextField(
                        blank=True, default="", verbose_name="above cutoff description"
                    ),
                ),
                (
                    "below_description",
                    models.TextField(
                        blank=True, default="", verbose_name="below cutoff description"
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cutoffs",
                        to="reporting.report",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        help_text="The variable (section) this cutoff applies to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_cutoffs",
                        to="assessment.assessmentsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "report cutoff",
                "verbose_name_plural": "report cutoffs",
                "ordering": ["section__level", "section__order"],
                "unique_together": {("report", "section")},
            },
        ),
        migrations.CreateModel(
            name="TypologicalCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Alphabet or number for code generation (e.g., 'A', '1')",
                        max_length=10,
                        verbose_name="code",
                    ),
                ),
                (
                    "top_n",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Number of top-scoring variables to include in the type profile.",
                        verbose_name="top N variables",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="typological_codes",
                        to="reporting.report",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        help_text="The variable (section) this code applies to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="typological_codes",
                        to="assessment.assessmentsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "typological code",
                "verbose_name_plural": "typological codes",
                "ordering": ["section__level", "section__order"],
                "unique_together": {("report", "section")},
            },
        ),
    ]
