# Generated by Django 5.0.6 on 2026-09-11 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_assessment_assessment_type'),
        ('reporting', '0002_report_data_input_level_report_include_fmi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pmi_d_first_assessment',
            field=models.CharField(blank=True, default='', help_text='Assessment label used as the minuend (A1) in PMI-D = A1PMI - A2PMI.', max_length=100, verbose_name='PMI-D first assessment (A1)'),
        ),
        migrations.AddField(
            model_name='report',
            name='pmi_d_second_assessment',
            field=models.CharField(blank=True, default='', help_text='Assessment label used as the subtrahend (A2) in PMI-D = A1PMI - A2PMI.', max_length=100, verbose_name='PMI-D second assessment (A2)'),
        ),
        migrations.AddField(
            model_name='reportband',
            name='assessment_label',
            field=models.CharField(blank=True, default='', help_text="For PMI/VMI bands: scopes the band to a single assessment (e.g., 'CAT'). Blank = applies to all assessments.", max_length=100, verbose_name='assessment label'),
        ),
        migrations.AddField(
            model_name='reportband',
            name='target_type',
            field=models.CharField(choices=[('section', 'Section score (interpretative)'), ('fmi', 'Final Match Index (FMI)'), ('pmi', 'Profile Match Index (PMI)'), ('vmi', 'Variable Match Index (VMI)'), ('raw_summary', 'Raw summary percentage'), ('pmi_d', 'PMI Gap Index (PMI-D)')], default='section', help_text='Which value this band interprets: section score, FMI, PMI, VMI, raw summary.', max_length=20, verbose_name='target type'),
        ),
        migrations.AlterField(
            model_name='reportband',
            name='section',
            field=models.ForeignKey(blank=True, help_text="The variable (section) this band applies to. Required for target_type='section'; leave blank for FMI/PMI/VMI/raw_summary bands.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_bands', to='assessment.assessmentsection'),
        ),
    ]
