# Generated by Django 5.0.6 on 2026-09-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_report_pmi_d_first_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsection',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Free-text description shown alongside this section (SRS §2.1.2).', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='reportsection',
            name='image',
            field=models.ImageField(blank=True, help_text='Uploaded image shown alongside this section (SRS §2.1.2).', null=True, upload_to='report_sections/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='reportsection',
            name='table_graph_config',
            field=models.JSONField(blank=True, help_text="JSON layout config: {'layout': 'table'|'graph', 'table_title': ..., 'variable_label': ..., 'score_label': ..., 'label_label': ..., 'colour_label': ..., 'description_label': ...}. 'table' is rendered end-to-end (section scores -> PDF table); 'graph' is recorded but not yet rendered (scoped out).", null=True, verbose_name='table/graph configuration'),
        ),
    ]
