# Generated by Django 5.0.6 on 2026-10-02 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_organization_enabled_modules'),
        ('reporting', '0004_reportsection_description_reportsection_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='owner_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_reports', to='organizations.organization'),
        ),
    ]
