# Generated by Django 5.0.6 on 2026-07-21 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('career', 'Career counselling'), ('learning', 'Learning difficulties'), ('emotional', 'Emotional problems'), ('relationship', 'Relationship problems'), ('marital', 'Marital problems'), ('clinical', 'Clinical problems'), ('health', 'Health counselling')], max_length=20, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'counseling category',
                'verbose_name_plural': 'counseling categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CounsellorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('bio', models.TextField(blank=True, default='', verbose_name='bio')),
                ('qualifications', models.TextField(blank=True, default='', verbose_name='qualifications')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=50, max_digits=10, verbose_name='hourly rate')),
                ('meeting_url', models.URLField(blank=True, default='', help_text='Zoom/Meet link for sessions', verbose_name='meeting URL')),
                ('is_available', models.BooleanField(default=True, verbose_name='available for booking')),
                ('cancellation_count', models.PositiveIntegerField(default=0, verbose_name='cancellation count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='counsellors', to='counseling.counselingcategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counsellor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'counsellor profile',
                'verbose_name_plural': 'counsellor profiles',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='CounselingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='topic')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='terms accepted')),
                ('status', models.CharField(choices=[('pending', 'Pending (awaiting counsellor confirmation)'), ('confirmed', 'Confirmed by counsellor'), ('completed', 'Session completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15, verbose_name='status')),
                ('payment_status', models.CharField(choices=[('pending', 'Payment Pending'), ('paid', 'Paid'), ('refunded_full', 'Refunded (100%)'), ('refunded_half', 'Refunded (50%)'), ('refunded_none', 'No refund')], default='pending', max_length=20, verbose_name='payment status')),
                ('mode', models.CharField(choices=[('online', 'Online (Zoom/Meet)'), ('offline', 'Offline (in-person)')], default='online', max_length=10, verbose_name='mode')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='fee')),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='counseling.counselingcategory')),
                ('counselee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_sessions_as_counselee', to=settings.AUTH_USER_MODEL)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='counseling.counsellorprofile')),
            ],
            options={
                'verbose_name': 'counseling session',
                'verbose_name_plural': 'counseling sessions',
                'ordering': ['-booked_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowupSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_time', models.DateTimeField(verbose_name='proposed time')),
                ('status', models.CharField(choices=[('proposed', 'Proposed (awaiting counselee payment)'), ('confirmed', 'Confirmed (payment done)'), ('declined', 'Declined by counselee')], default='proposed', max_length=15, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_followup', to='counseling.counselingsession')),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_sessions', to='counseling.counsellorprofile')),
                ('original_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='counseling.counselingsession')),
            ],
            options={
                'verbose_name': 'follow-up session',
                'verbose_name_plural': 'follow-up sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled_by', models.CharField(choices=[('counselee', 'Cancelled by counselee'), ('counsellor', 'Cancelled by counsellor')], max_length=15, verbose_name='cancelled by')),
                ('reason', models.TextField(blank=True, default='', verbose_name='reason')),
                ('refund_tier', models.CharField(choices=[('full', 'Full refund (100%)'), ('half', 'Half refund (50%)'), ('none', 'No refund')], default='none', max_length=10, verbose_name='refund tier')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='refund amount')),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='counseling.counselingsession')),
            ],
            options={
                'verbose_name': 'session cancellation',
                'verbose_name_plural': 'session cancellations',
            },
        ),
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(verbose_name='rating (1-5)')),
                ('experience_text', models.TextField(verbose_name='experience feedback')),
                ('counsellor_effectiveness', models.TextField(blank=True, default='', verbose_name='counsellor effectiveness')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counselee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='counseling.counselingsession')),
            ],
            options={
                'verbose_name': 'session feedback',
                'verbose_name_plural': 'session feedbacks',
            },
        ),
        migrations.CreateModel(
            name='SessionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(verbose_name='session summary')),
                ('recommendations', models.TextField(blank=True, default='', verbose_name='recommendations')),
                ('followup_recommended', models.BooleanField(default=False, verbose_name='follow-up recommended')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counsellor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_summaries', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='counseling.counselingsession')),
            ],
            options={
                'verbose_name': 'session summary',
                'verbose_name_plural': 'session summaries',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked (session pending)'), ('blocked', 'Blocked (counsellor unavailable)')], default='available', max_length=10, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='counseling.counsellorprofile')),
            ],
            options={
                'verbose_name': 'time slot',
                'verbose_name_plural': 'time slots',
                'ordering': ['start_time'],
                'unique_together': {('counsellor', 'start_time')},
            },
        ),
        migrations.AddField(
            model_name='counselingsession',
            name='timeslot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='counseling.timeslot'),
        ),
    ]
