# Generated by Django 5.0.6 on 2026-07-24 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counsellorprofile',
            options={'ordering': ['user__full_name'], 'verbose_name': 'counsellor profile', 'verbose_name_plural': 'counsellor profiles'},
        ),
        migrations.RemoveField(
            model_name='counsellorprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='counsellorprofile',
            name='cancellation_count',
        ),
        migrations.RemoveField(
            model_name='counsellorprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='counsellorprofile',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='counsellorprofile',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='counsellorprofile',
            name='meeting_url',
        ),
        migrations.RemoveField(
            model_name='counsellorprofile',
            name='qualifications',
        ),
    ]
