# Generated by Django 5.0.6 on 2026-08-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0002_counsellor_fields_on_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_and_conditions', models.TextField(blank=True, default='', help_text='Shown on booking.', verbose_name='terms and conditions')),
                ('cancellation_refund_policy', models.TextField(blank=True, default='', help_text='Shown before cancel.', verbose_name='cancellation & refund policy')),
                ('max_weeks_ahead', models.PositiveIntegerField(default=3, help_text='Counsellors cannot create timeslots further than this many weeks out.', verbose_name='max weeks ahead for timeslots')),
                ('confirm_window_hours', models.PositiveIntegerField(default=6, help_text='A pending booking auto-cancels after this many hours unconfirmed.', verbose_name='confirm window (hours)')),
                ('full_refund_within_hours', models.PositiveIntegerField(default=24, verbose_name='full refund if cancelled > N hours before')),
                ('half_refund_within_hours', models.PositiveIntegerField(default=4, verbose_name='half refund if cancelled > N hours before')),
            ],
            options={
                'verbose_name': 'counseling settings',
                'verbose_name_plural': 'counseling settings',
            },
        ),
        migrations.AddField(
            model_name='sessionfeedback',
            name='counsellor_empathy',
            field=models.CharField(blank=True, choices=[('very_much', 'Very much'), ('somewhat', 'Somewhat'), ('not_much', 'Not much')], default='', max_length=20, verbose_name='counsellor friendly & empathetic?'),
        ),
        migrations.AddField(
            model_name='sessionfeedback',
            name='improvement_suggestions',
            field=models.TextField(blank=True, default='', verbose_name='how can we improve the service'),
        ),
        migrations.AddField(
            model_name='sessionfeedback',
            name='rechoose_reason',
            field=models.TextField(blank=True, default='', verbose_name='why would you (re)choose or not'),
        ),
        migrations.AddField(
            model_name='sessionfeedback',
            name='session_ended',
            field=models.CharField(blank=True, choices=[('on_time', 'Ended on time'), ('before_time', 'Ended before time'), ('ended_late', 'Ended late')], default='', max_length=20, verbose_name='how did the session end?'),
        ),
        migrations.AddField(
            model_name='sessionfeedback',
            name='session_useful',
            field=models.CharField(blank=True, choices=[('very_useful', 'Very useful'), ('useful', 'Useful'), ('somewhat_useful', 'Somewhat useful'), ('not_useful', 'Not useful')], default='', max_length=20, verbose_name='was the session useful?'),
        ),
        migrations.AddField(
            model_name='sessionfeedback',
            name='useful_reason',
            field=models.TextField(blank=True, default='', verbose_name='why useful / not useful'),
        ),
        migrations.AddField(
            model_name='sessionfeedback',
            name='would_rechoose',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('maybe', 'Maybe'), ('no', 'No')], default='', max_length=20, verbose_name='would you choose this counsellor again?'),
        ),
        migrations.AddField(
            model_name='sessionsummary',
            name='case_prognosis',
            field=models.TextField(blank=True, default='', verbose_name='case prognosis'),
        ),
        migrations.AddField(
            model_name='sessionsummary',
            name='client_details',
            field=models.TextField(blank=True, default='', verbose_name='client details and problem description'),
        ),
        migrations.AddField(
            model_name='sessionsummary',
            name='provisional_diagnosis',
            field=models.TextField(blank=True, default='', verbose_name='provisional diagnosis'),
        ),
        migrations.AddField(
            model_name='sessionsummary',
            name='session_smoothly',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('somewhat', 'Somewhat'), ('no', 'No')], default='', max_length=20, verbose_name='did the session go smoothly?'),
        ),
        migrations.AddField(
            model_name='sessionsummary',
            name='smoothly_reason',
            field=models.TextField(blank=True, default='', verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='sessionfeedback',
            name='experience_text',
            field=models.TextField(blank=True, default='', verbose_name='experience feedback'),
        ),
        migrations.AlterField(
            model_name='sessionfeedback',
            name='rating',
            field=models.PositiveIntegerField(verbose_name='rating (1-10)'),
        ),
    ]
