# Generated by Django 5.0.6 on 2026-08-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counseling", "0002_counsellor_fields_on_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="CounselingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "terms_and_conditions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Terms & Conditions for counseling. Shown to candidate on booking.",
                        verbose_name="terms and conditions",
                    ),
                ),
                (
                    "cancellation_policy",
                    models.TextField(
                        blank=True,
                        default="Before 24 hours: full refund. Before 4 hours: 50% refund. Less than 4 hours: no refund.",
                        help_text="Cancellation and refund policy. Shown to candidate before cancellation.",
                        verbose_name="cancellation/refund policy",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "counseling settings",
                "verbose_name_plural": "counseling settings",
            },
        ),
        migrations.AddField(
            model_name="sessionfeedback",
            name="counsellor_empathy",
            field=models.CharField(
                choices=[
                    ("very_much", "Very much"),
                    ("somewhat", "Somewhat"),
                    ("not_much", "Not much"),
                ],
                default="somewhat",
                max_length=20,
                verbose_name="counsellor empathy",
            ),
        ),
        migrations.AddField(
            model_name="sessionfeedback",
            name="counsellor_rating",
            field=models.PositiveIntegerField(default=5, verbose_name="counsellor rating (1-10)"),
        ),
        migrations.AddField(
            model_name="sessionfeedback",
            name="improvement_suggestions",
            field=models.TextField(blank=True, default="", verbose_name="improvement suggestions"),
        ),
        migrations.AddField(
            model_name="sessionfeedback",
            name="rechoose_text",
            field=models.TextField(blank=True, default="", verbose_name="rechoose explanation"),
        ),
        migrations.AddField(
            model_name="sessionfeedback",
            name="session_ending",
            field=models.CharField(
                choices=[
                    ("on_time", "Ended on time"),
                    ("before_time", "Ended before time"),
                    ("late", "Ended late"),
                ],
                default="on_time",
                max_length=20,
                verbose_name="session ending",
            ),
        ),
        migrations.AddField(
            model_name="sessionfeedback",
            name="session_usefulness",
            field=models.CharField(
                choices=[
                    ("very_useful", "Very useful"),
                    ("useful", "Useful"),
                    ("somewhat_useful", "Somewhat useful"),
                    ("not_useful", "Not useful"),
                ],
                default="useful",
                max_length=20,
                verbose_name="session usefulness",
            ),
        ),
        migrations.AddField(
            model_name="sessionfeedback",
            name="usefulness_text",
            field=models.TextField(blank=True, default="", verbose_name="usefulness explanation"),
        ),
        migrations.AddField(
            model_name="sessionfeedback",
            name="would_rechoose",
            field=models.CharField(
                choices=[("yes", "Yes"), ("maybe", "May be"), ("no", "No")],
                default="maybe",
                max_length=10,
                verbose_name="would rechoose counsellor",
            ),
        ),
        migrations.AddField(
            model_name="sessionsummary",
            name="case_prognosis",
            field=models.TextField(blank=True, default="", verbose_name="case prognosis"),
        ),
        migrations.AddField(
            model_name="sessionsummary",
            name="client_details",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Client details and problem description (mandatory)",
                verbose_name="client details and problem description",
            ),
        ),
        migrations.AddField(
            model_name="sessionsummary",
            name="provisional_diagnosis",
            field=models.TextField(blank=True, default="", verbose_name="provisional diagnosis"),
        ),
        migrations.AddField(
            model_name="sessionsummary",
            name="session_smoothness",
            field=models.CharField(
                choices=[("yes", "Yes"), ("somewhat", "Somewhat"), ("no", "No")],
                default="yes",
                max_length=10,
                verbose_name="session smoothness",
            ),
        ),
        migrations.AddField(
            model_name="sessionsummary",
            name="smoothness_reason",
            field=models.TextField(
                blank=True, default="", verbose_name="reason for smoothness rating"
            ),
        ),
        migrations.AlterField(
            model_name="sessionfeedback",
            name="experience_text",
            field=models.TextField(blank=True, default="", verbose_name="experience feedback"),
        ),
        migrations.AlterField(
            model_name="sessionfeedback",
            name="rating",
            field=models.PositiveIntegerField(default=3, verbose_name="rating (1-5)"),
        ),
    ]
