# Generated by Django 5.0.6 on 2026-08-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0003_counselingsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselingsettings',
            name='confirm_window_hours',
            field=models.PositiveIntegerField(default=6, verbose_name='confirm window (hours)'),
        ),
        migrations.AddField(
            model_name='counselingsettings',
            name='full_refund_within_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='full refund if cancelled > N hours before'),
        ),
        migrations.AddField(
            model_name='counselingsettings',
            name='half_refund_within_hours',
            field=models.PositiveIntegerField(default=4, verbose_name='half refund if cancelled > N hours before'),
        ),
        migrations.AddField(
            model_name='counselingsettings',
            name='max_weeks_ahead',
            field=models.PositiveIntegerField(default=3, verbose_name='max weeks ahead for timeslots'),
        ),
    ]
