# Generated by Django 5.0.6 on 2026-09-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0004_counselingsettings_confirm_window_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselingsession',
            name='meeting_link',
            field=models.URLField(blank=True, default='', help_text='Per-session Zoom/Meet link set by the counsellor for this booking.', verbose_name='meeting link'),
        ),
    ]
