# Generated by Django 5.0.6 on 2026-09-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0005_counselingsession_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselingsession',
            name='actual_end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='actual end time'),
        ),
        migrations.AddField(
            model_name='counselingsession',
            name='actual_start_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='actual start time'),
        ),
        migrations.AddField(
            model_name='sessioncancellation',
            name='refund_executed',
            field=models.BooleanField(default=False, verbose_name='refund executed'),
        ),
    ]
