# Generated by Django 5.0.6 on 2026-10-02 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0006_counselingsession_actual_end_at_and_more'),
        ('organizations', '0004_assessmentschedule_corporatewebsite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='counselingsession',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_counseling_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='counselingsession',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counseling_sessions', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='sessioncancellation',
            name='cancelled_by',
            field=models.CharField(choices=[('counselee', 'Cancelled by counselee'), ('counsellor', 'Cancelled by counsellor'), ('organization', 'Cancelled by the organization')], max_length=15, verbose_name='cancelled by'),
        ),
    ]
