# Generated by Django 5.0.6 on 2026-10-02 23:06

from django.db import migrations, models

# Report 9 #105: the Doc 8 categories that used to be fixed in code (choices on
# CounselingCategory.name). Frozen here so the migration never depends on the
# model module.
DEFAULT_CATEGORIES = [
    ("career", "Career counselling"),
    ("learning", "Learning difficulties"),
    ("emotional", "Emotional problems"),
    ("relationship", "Relationship problems"),
    ("marital", "Marital problems"),
    ("clinical", "Clinical problems"),
    ("health", "Health counselling"),
]


def seed_categories(apps, schema_editor):
    """Give every existing category its label (rows keep their id and code, so
    counsellor tags and session categories are untouched) and create the
    Doc 8 categories that do not exist yet."""
    Category = apps.get_model("counseling", "CounselingCategory")
    labels = dict(DEFAULT_CATEGORIES)
    for category in Category.objects.all():
        if not category.label:
            category.label = labels.get(category.name, category.name)
            category.save(update_fields=["label"])
    for code, label in DEFAULT_CATEGORIES:
        Category.objects.get_or_create(name=code, defaults={"label": label})


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0007_session_organization_booked_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counselingcategory',
            options={'ordering': ['label', 'name'], 'verbose_name': 'counseling category', 'verbose_name_plural': 'counseling categories'},
        ),
        migrations.AddField(
            model_name='counselingcategory',
            name='label',
            field=models.CharField(default='', max_length=100, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='counselingcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='code'),
        ),
        migrations.RunPython(seed_categories, migrations.RunPython.noop),
    ]
