# Generated by Django 5.0.6 on 2026-10-03 05:42

from django.db import migrations, models
from django.utils import timezone


def reopen_cancelled_slots(apps, schema_editor):
    """Code review: a cancelled session used to set its slot back to
    'available' while still holding it (one session per slot), so the slot was
    listed but could not be booked. Mark those slots 'cancelled' (they keep the
    cancelled session) and open a fresh available slot for future times."""
    TimeSlot = apps.get_model("counseling", "TimeSlot")
    now = timezone.now()
    stale = TimeSlot.objects.filter(status="available", session__status="cancelled")
    for slot in stale:
        slot.status = "cancelled"
        slot.save(update_fields=["status"])
        if slot.start_time > now:
            TimeSlot.objects.create(
                counsellor_id=slot.counsellor_id,
                start_time=slot.start_time,
                end_time=slot.end_time,
                status="available",
            )


class Migration(migrations.Migration):

    dependencies = [
        ("counseling", "0008_categories_managed_by_admin"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="timeslot",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("booked", "Booked (session pending)"),
                    ("blocked", "Blocked (counsellor unavailable)"),
                    ("cancelled", "Cancelled (session cancelled)"),
                ],
                default="available",
                max_length=10,
                verbose_name="status",
            ),
        ),
        migrations.AddConstraint(
            model_name="timeslot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "cancelled"), _negated=True),
                fields=("counsellor", "start_time"),
                name="uniq_live_timeslot_per_counsellor_start",
            ),
        ),
        migrations.RunPython(reopen_cancelled_slots, migrations.RunPython.noop),
    ]
