# Generated by Django 5.0.6 on 2026-07-24 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, default='', max_length=500, verbose_name='subtitle')),
                ('body', models.TextField(blank=True, default='', help_text='HTML or text content', verbose_name='body')),
                ('image', models.TextField(blank=True, default='', help_text='URL or base64 data URL', verbose_name='image')),
                ('link_url', models.URLField(blank=True, default='', help_text='Click-through URL', verbose_name='link URL')),
                ('link_text', models.CharField(blank=True, default='Learn more', max_length=100, verbose_name='link text')),
                ('position', models.CharField(choices=[('hero', 'Hero (top of homepage)'), ('sidebar', 'Sidebar'), ('footer', 'Footer'), ('inline', 'Inline (between content)')], default='hero', max_length=20, verbose_name='position')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='starts at')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='ends at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_banners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                ('url', models.CharField(help_text='Internal path or external URL', max_length=500, verbose_name='URL')),
                ('location', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('sidebar', 'Sidebar')], default='header', max_length=20, verbose_name='location')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('opens_new_tab', models.BooleanField(default=False, verbose_name='opens in new tab')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent menu item for dropdowns', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.menuitem')),
            ],
            options={
                'verbose_name': 'menu item',
                'verbose_name_plural': 'menu items',
                'ordering': ['location', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(help_text="URL path, e.g., 'about'", max_length=255, unique=True, verbose_name='slug')),
                ('body', models.TextField(help_text='HTML or markdown content', verbose_name='body')),
                ('meta_description', models.CharField(blank=True, default='', max_length=500, verbose_name='meta description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='status')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'ordering': ['order', 'title'],
            },
        ),
    ]
