# Generated by Django 5.0.6 on 2026-09-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('general', 'General page'), ('terms', 'Terms & Conditions'), ('refund', 'Refund Policy'), ('privacy', 'Privacy Policy')], default='general', max_length=20, verbose_name='page type'),
        ),
    ]
