# Generated by Django 5.0.6 on 2026-07-20 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0002_assessment_assessment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('week_number', models.PositiveIntegerField(default=1, verbose_name='week number')),
            ],
            options={
                'verbose_name': 'course lesson',
                'verbose_name_plural': 'course lessons',
                'ordering': ['week_number', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'training category',
                'verbose_name_plural': 'training categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LessonTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='training.courselesson')),
            ],
            options={
                'verbose_name': 'lesson topic',
                'verbose_name_plural': 'lesson topics',
                'ordering': ['order'],
                'unique_together': {('lesson', 'order')},
            },
        ),
        migrations.CreateModel(
            name='TopicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='training.lessontopic')),
            ],
            options={
                'verbose_name': 'topic session',
                'verbose_name_plural': 'topic sessions',
                'ordering': ['order'],
                'unique_together': {('topic', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('resource_url', models.URLField(blank=True, default='', verbose_name='resource URL')),
                ('report_submission_enabled', models.BooleanField(default=False, verbose_name='report submission enabled')),
                ('report_instructions', models.TextField(blank=True, default='', verbose_name='report instructions')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='training.topicsession')),
            ],
            options={
                'verbose_name': 'assignment',
                'verbose_name_plural': 'assignments',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('objective', models.TextField(blank=True, default='', verbose_name='objective')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('image', models.TextField(blank=True, default='', help_text='URL or base64 data URL of course image', verbose_name='image')),
                ('course_type', models.CharField(choices=[('online_standard', 'Online Standard (media-based)'), ('online_live', 'Online Live (Zoom classroom)'), ('offline_live', 'Offline Live (classroom)')], default='online_standard', max_length=20, verbose_name='course type')),
                ('schedule_type', models.CharField(choices=[('scheduled', 'Scheduled (fixed duration)'), ('non_scheduled', 'Non-Scheduled (self-paced)')], default='non_scheduled', max_length=20, verbose_name='schedule type')),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text='Total duration allowed for course completion (scheduled courses only)', null=True, verbose_name='duration (days)')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Registration price', max_digits=10, verbose_name='price')),
                ('status', models.CharField(choices=[('draft', 'Draft (being configured)'), ('published', 'Published (available for registration)'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='training.trainingcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'training course',
                'verbose_name_plural': 'training courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('mode', models.CharField(choices=[('online', 'Online (Zoom)'), ('offline', 'Offline (Classroom)')], default='online', max_length=10, verbose_name='mode')),
                ('meeting_url', models.URLField(blank=True, default='', verbose_name='meeting URL')),
                ('venue', models.CharField(blank=True, default='', max_length=255, verbose_name='venue')),
                ('scheduled_at', models.DateTimeField(verbose_name='scheduled at')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='duration (minutes)')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='training.trainingcourse')),
            ],
            options={
                'verbose_name': 'live session',
                'verbose_name_plural': 'live sessions',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('pending', 'Payment Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('failed', 'Payment Failed')], default='pending', max_length=20, verbose_name='payment status')),
                ('completion_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired (duration elapsed)')], default='not_started', max_length=20, verbose_name='completion status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_registrations', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='training.trainingcourse')),
            ],
            options={
                'verbose_name': 'course registration',
                'verbose_name_plural': 'course registrations',
                'ordering': ['-registered_at'],
                'unique_together': {('course', 'student')},
            },
        ),
        migrations.AddField(
            model_name='courselesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='training.trainingcourse'),
        ),
        migrations.CreateModel(
            name='CourseAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('during_session', 'During Session'), ('end_of_session', 'End of Session'), ('end_of_topic', 'End of Topic'), ('end_of_lesson', 'End of Lesson'), ('end_of_course', 'End of Course')], default='end_of_session', max_length=20, verbose_name='level')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('is_scored', models.BooleanField(default=True, verbose_name='is scored')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_course_assessments', to='assessment.assessment')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='training.topicsession')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='training.trainingcourse')),
            ],
            options={
                'verbose_name': 'course assessment',
                'verbose_name_plural': 'course assessments',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('session_content', 'Session Content'), ('assignment', 'Assignment'), ('assessment', 'Assessment'), ('live_session', 'Live Session')], max_length=20, verbose_name='content type')),
                ('content_id', models.PositiveIntegerField(verbose_name='content ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='is completed')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='time spent (seconds)')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='last accessed at')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='training.courseregistration')),
            ],
            options={
                'verbose_name': 'course progress',
                'verbose_name_plural': 'course progress records',
                'unique_together': {('registration', 'content_type', 'content_id')},
            },
        ),
        migrations.CreateModel(
            name='SessionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('content_format', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('text', 'Text')], default='video', max_length=10, verbose_name='content format')),
                ('content_url', models.TextField(blank=True, default='', help_text='URL or base64 data URL', verbose_name='content URL')),
                ('text_content', models.TextField(blank=True, default='', verbose_name='text content')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='duration (seconds)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='training.topicsession')),
            ],
            options={
                'verbose_name': 'session content',
                'verbose_name_plural': 'session contents',
                'ordering': ['order'],
                'unique_together': {('session', 'order')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='courselesson',
            unique_together={('course', 'order')},
        ),
        migrations.CreateModel(
            name='CourseCompletionParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('session_content', 'Session Content'), ('assignment', 'Assignment'), ('assessment', 'Assessment'), ('live_session', 'Live Session')], max_length=20, verbose_name='content type')),
                ('content_id', models.PositiveIntegerField(verbose_name='content ID')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='is mandatory')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_parameters', to='training.trainingcourse')),
            ],
            options={
                'verbose_name': 'course completion parameter',
                'verbose_name_plural': 'course completion parameters',
                'unique_together': {('course', 'content_type', 'content_id')},
            },
        ),
    ]
