# Generated by Django 5.0.6 on 2026-07-20 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioncontent',
            name='sequence_order',
            field=models.PositiveIntegerField(blank=True, help_text='Override order for interlinked playback (SRS §2.4.1.1). Null = use default order.', null=True, verbose_name='sequence order'),
        ),
        migrations.CreateModel(
            name='CourseMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='message body')),
                ('is_read', models.BooleanField(default=False, verbose_name='read by recipient')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='training.courseregistration')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_training_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'course message',
                'verbose_name_plural': 'course messages',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField(blank=True, default='', verbose_name='report text')),
                ('report_file_url', models.TextField(blank=True, default='', help_text='URL or base64 data URL of the uploaded report file', verbose_name='report file URL')),
                ('status', models.CharField(choices=[('submitted', 'Submitted (awaiting trainer review)'), ('reviewed', 'Reviewed by trainer'), ('resubmitted', 'Resubmitted by student (after trainer feedback)')], default='submitted', max_length=20, verbose_name='status')),
                ('trainer_score', models.FloatField(blank=True, help_text='Score given by trainer (0-100)', null=True, verbose_name='trainer score')),
                ('trainer_feedback', models.TextField(blank=True, default='', verbose_name='trainer feedback')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='training.assignment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assignment_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'assignment report',
                'verbose_name_plural': 'assignment reports',
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
