# Generated by Django 5.0.6 on 2026-07-21 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_reports_messages_interlinking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='question text')),
                ('trigger_timestamp', models.FloatField(help_text='Seconds into the media when this question should appear', verbose_name='trigger timestamp (seconds)')),
                ('options', models.JSONField(default=list, help_text='List of {"id": int, "text": str, "is_correct": bool} objects', verbose_name='options')),
                ('correct_jump_to', models.FloatField(help_text='Timestamp to jump to if answered correctly', verbose_name='correct answer jump-to (seconds)')),
                ('incorrect_jump_to', models.FloatField(help_text='Timestamp to jump to if answered incorrectly', verbose_name='incorrect answer jump-to (seconds)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('session_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive_questions', to='training.sessioncontent')),
            ],
            options={
                'verbose_name': 'interactive question',
                'verbose_name_plural': 'interactive questions',
                'ordering': ['trigger_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LiveSessionConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('consented', 'Consented (will attend)'), ('declined', 'Declined (will not attend)')], default='consented', max_length=10, verbose_name='status')),
                ('consented_at', models.DateTimeField(auto_now=True)),
                ('live_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='training.livesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_session_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'live session consent',
                'verbose_name_plural': 'live session consents',
                'ordering': ['-consented_at'],
                'unique_together': {('live_session', 'student')},
            },
        ),
    ]
