# Generated by Django 5.0.6 on 2026-08-08 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0003_consent_interactive"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="is_mandatory",
            field=models.BooleanField(
                default=False,
                help_text="If True, candidate cannot proceed to next session/topic/lesson until report is submitted.",
                verbose_name="is mandatory",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="submission_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Last date/time for report submission. After deadline, special trainer permission required.",
                null=True,
                verbose_name="submission deadline",
            ),
        ),
        migrations.AddField(
            model_name="assignmentreport",
            name="report_file_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="File type of uploaded report: pdf, ppt, word, etc.",
                max_length=20,
                verbose_name="report file type",
            ),
        ),
        migrations.AddField(
            model_name="trainingcourse",
            name="content_sequencing_enabled",
            field=models.BooleanField(
                default=False,
                help_text="If True, candidate must complete contents in sequential order. Cannot skip.",
                verbose_name="content sequencing enabled",
            ),
        ),
        migrations.AlterField(
            model_name="assignmentreport",
            name="report_file_url",
            field=models.TextField(
                blank=True,
                default="",
                help_text="URL or base64 data URL of the uploaded report file (PDF/PPT/Word)",
                verbose_name="report file URL",
            ),
        ),
        migrations.AlterField(
            model_name="assignmentreport",
            name="trainer_score",
            field=models.FloatField(
                blank=True,
                help_text="Score given by trainer (0-10 scale)",
                null=True,
                verbose_name="trainer score",
            ),
        ),
        migrations.CreateModel(
            name="CourseModificationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[("update", "Course Update"), ("delete", "Course Deletion")],
                        max_length=10,
                        verbose_name="request type",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Reason for the update/delete request", verbose_name="reason"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Admin Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "review_comment",
                    models.TextField(blank=True, default="", verbose_name="review comment"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="reviewed at"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modification_requests",
                        to="training.trainingcourse",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="course_modification_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_modification_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "course modification request",
                "verbose_name_plural": "course modification requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionReschedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("old_start_time", models.DateTimeField(verbose_name="old start time")),
                ("new_start_time", models.DateTimeField(verbose_name="new start time")),
                (
                    "reason",
                    models.TextField(help_text="Reason for rescheduling", verbose_name="reason"),
                ),
                (
                    "push_forward_remaining",
                    models.BooleanField(
                        default=False,
                        help_text="If True, all subsequent live sessions are shifted by the same delta.",
                        verbose_name="push forward remaining sessions",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "live_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reschedules",
                        to="training.livesession",
                    ),
                ),
                (
                    "rescheduled_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_reschedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "session reschedule",
                "verbose_name_plural": "session reschedules",
                "ordering": ["-created_at"],
            },
        ),
    ]
