# Generated by Django 5.0.6 on 2026-08-21 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_assignment_is_mandatory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentreport',
            name='late_submission_approved',
            field=models.BooleanField(default=False, verbose_name='late submission approved'),
        ),
        migrations.AddField(
            model_name='assignmentreport',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='assignment_reports/', verbose_name='report file upload'),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='registration_form',
            field=models.JSONField(blank=True, default=dict, verbose_name='registration form'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_sessions', to='training.livesession'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='reschedule_reason',
            field=models.TextField(blank=True, default='', verbose_name='reschedule reason'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='rescheduled_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='rescheduled from'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='schedule_mode',
            field=models.CharField(choices=[('advance', 'Advance'), ('ongoing', 'Ongoing')], default='advance', max_length=10, verbose_name='schedule mode'),
        ),
        migrations.AddField(
            model_name='sessioncontent',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='session_documents/', verbose_name='document'),
        ),
        migrations.CreateModel(
            name='LiveSessionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_times', models.JSONField(blank=True, default=list, verbose_name='preferred times')),
                ('note', models.TextField(blank=True, default='', verbose_name='note')),
                ('status', models.CharField(choices=[('pending', 'Pending - trainer has not scheduled yet'), ('scheduled', 'Trainer scheduled a session'), ('declined', 'Trainer declined')], default='pending', max_length=10, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_session_requests', to='training.trainingcourse')),
                ('scheduled_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_requests', to='training.livesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_session_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'live session request',
                'verbose_name_plural': 'live session requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
