# Generated by Django 5.0.6 on 2026-09-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_report3_training_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioncontent',
            name='media_file',
            field=models.FileField(blank=True, help_text='Uploaded media file (video/audio/image) for this content.', null=True, upload_to='session_media/', verbose_name='media file upload'),
        ),
    ]
