# Generated by Django 5.0.6 on 2026-09-18 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_sessioncontent_media_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assignment_reports/', verbose_name='file')),
                ('file_type', models.CharField(blank=True, default='', max_length=20, verbose_name='file type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='training.assignmentreport')),
            ],
            options={
                'verbose_name': 'assignment report file',
                'verbose_name_plural': 'assignment report files',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentDeadlineOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_deadline', models.DateTimeField(verbose_name='new deadline')),
                ('reason', models.CharField(blank=True, default='', max_length=500, verbose_name='reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_overrides', to='training.assignment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deadline_overrides', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_deadline_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'assignment deadline override',
                'verbose_name_plural': 'assignment deadline overrides',
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
