# Generated by Django 5.0.6 on 2026-09-18 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_assignmentreportfile_assignmentdeadlineoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassessment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='training.courselesson'),
        ),
        migrations.AddField(
            model_name='courseassessment',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='training.lessontopic'),
        ),
    ]
