# Generated by Django 5.0.6 on 2026-09-29 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_courseassessment_lesson_courseassessment_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesessionrequest',
            name='live_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests', to='training.livesession'),
        ),
    ]
