# Generated by Django 5.0.6 on 2026-09-29 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_live_session_request_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='after_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_sessions_after', to='training.sessioncontent'),
        ),
    ]
