# Generated by Django 5.0.6 on 2026-10-02 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_assessmentschedule_corporatewebsite'),
        ('training', '0010_live_session_after_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_course_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_registrations', to='organizations.organization'),
        ),
    ]
