# Generated by Django 5.0.6 on 2026-10-02 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_courseregistration_organization_assigned_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name': 'trainer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trained_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
