# Generated by Django 5.0.6 on 2026-10-02 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_organization_enabled_modules'),
        ('training', '0011_courseregistration_organization_assigned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='owner_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_training_courses', to='organizations.organization'),
        ),
    ]
