# Generated by Django 5.0.6 on 2026-10-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_private_owner_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodificationrequest',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='editing finished at'),
        ),
    ]
