# Generated by Django 5.0.6 on 2026-06-30 11:41

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("cj_admin", "CareerJudge Admin"),
                            ("corp_admin", "Corporate Admin"),
                            ("corp_exclusive", "Corporate Exclusive"),
                            ("psychometrician", "Psychometrician"),
                            ("sme_reviewer", "SME / Reviewer"),
                            ("trainer", "Trainer"),
                            ("group_admin", "Group Admin"),
                            ("counsellor", "Counsellor"),
                            ("individual", "Individual"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "is_frozen",
                    models.BooleanField(
                        default=False,
                        help_text="Frozen roles accept additive permission grants only.",
                        verbose_name="frozen",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "role",
                "verbose_name_plural": "roles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="email address"),
                ),
                (
                    "full_name",
                    models.CharField(blank=True, max_length=255, verbose_name="full name"),
                ),
                (
                    "is_email_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has verified their email via activation link.",
                        verbose_name="email verified",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="phone")),
                (
                    "is_trial_user",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this user is on a trial plan.",
                        verbose_name="trial user",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary role for this user. Additional module-specific rights via ModuleRight.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("non_binary", "Non-binary"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=20,
                        verbose_name="gender",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(blank=True, null=True, verbose_name="date of birth"),
                ),
                ("mobile", models.CharField(blank=True, max_length=15, verbose_name="mobile")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/", verbose_name="avatar"
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(blank=True, max_length=255, verbose_name="address line 1"),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=255, verbose_name="address line 2"),
                ),
                ("city", models.CharField(blank=True, max_length=100, verbose_name="city")),
                ("state", models.CharField(blank=True, max_length=100, verbose_name="state")),
                ("country", models.CharField(blank=True, max_length=100, verbose_name="country")),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=20, verbose_name="postal code"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="bio")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user profile",
                "verbose_name_plural": "user profiles",
            },
        ),
        migrations.CreateModel(
            name="ModuleRight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("accounts", "Accounts"),
                            ("organizations", "Organizations"),
                            ("question_bank", "Question Bank"),
                            ("assessment", "Assessment"),
                            ("career_profiling", "Career Profiling"),
                            ("reporting", "Reporting"),
                            ("training", "Training"),
                            ("counseling", "Counseling"),
                            ("cms", "CMS"),
                            ("notifications", "Notifications"),
                        ],
                        max_length=50,
                        verbose_name="module",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("add", "Add"),
                            ("change", "Change"),
                            ("delete", "Delete"),
                            ("approve", "Approve"),
                            ("assign", "Assign"),
                            ("export", "Export"),
                            ("generate_report", "Generate Report"),
                        ],
                        max_length=50,
                        verbose_name="action",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rights",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "module right",
                "verbose_name_plural": "module rights",
                "ordering": ["module", "action"],
                "unique_together": {("role", "module", "action")},
            },
        ),
    ]
