# Generated by Django 5.0.6 on 2026-06-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moduleright",
            name="action",
            field=models.CharField(
                choices=[
                    ("view", "View"),
                    ("add", "Add"),
                    ("change", "Change"),
                    ("delete", "Delete"),
                    ("approve", "Approve"),
                    ("reject", "Reject"),
                    ("review", "Review"),
                    ("assign", "Assign"),
                    ("export", "Export"),
                    ("generate_report", "Generate Report"),
                    ("request_delete", "Request Deletion"),
                ],
                max_length=50,
                verbose_name="action",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("cj_admin", "CareerJudge Admin"),
                    ("corp_admin", "Corporate Admin"),
                    ("corp_exclusive", "Corporate Exclusive"),
                    ("psychometrician", "Psychometrician"),
                    ("sme", "SME (Subject Matter Expert)"),
                    ("reviewer", "Reviewer"),
                    ("trainer", "Trainer"),
                    ("group_admin", "Group Admin"),
                    ("counsellor", "Counsellor"),
                    ("individual", "Individual"),
                ],
                max_length=50,
                unique=True,
                verbose_name="name",
            ),
        ),
    ]
