# Generated by Django 5.0.6 on 2026-07-01 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_moduleright_action_alter_role_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="base_role",
            field=models.ForeignKey(
                blank=True,
                help_text="For custom roles: the system role whose permissions are inherited and cannot be removed.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="custom_roles",
                to="accounts.role",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="is_system",
            field=models.BooleanField(
                default=False,
                help_text="System roles are the 10 built-in roles. Cannot be deleted or have permissions modified.",
                verbose_name="system role",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="is_frozen",
            field=models.BooleanField(
                default=False,
                help_text="Frozen roles' permissions cannot be modified. System roles are always frozen.",
                verbose_name="frozen",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="name"),
        ),
    ]
