# Generated by Django 5.0.6 on 2026-07-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_userprofile_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="country",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="state",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="assessment_package_allocated",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="assessment package allocated"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=15, verbose_name="bank account number"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bank_name",
            field=models.CharField(blank=True, max_length=20, verbose_name="bank name"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="branch_name",
            field=models.CharField(blank=True, max_length=25, verbose_name="branch name"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="channel_partner_agreement_id",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="channel partner agreement ID"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="contact_address",
            field=models.TextField(blank=True, max_length=100, verbose_name="contact address"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="contract_period",
            field=models.CharField(blank=True, max_length=2, verbose_name="contract period"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="country_of_origin",
            field=models.CharField(blank=True, max_length=50, verbose_name="country of origin"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="current_position",
            field=models.CharField(blank=True, max_length=50, verbose_name="current position"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="domain_experience",
            field=models.CharField(blank=True, max_length=2, verbose_name="domain experience"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("5-12", "5-12"),
                    ("undergraduate", "Undergraduate"),
                    ("post_graduate", "Post Graduate"),
                    ("m_phil", "M-Phil"),
                    ("phd", "PhD"),
                ],
                max_length=20,
                verbose_name="education level",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="first name"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="highest_education",
            field=models.CharField(blank=True, max_length=50, verbose_name="highest education"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="ifsc_code",
            field=models.CharField(blank=True, max_length=15, verbose_name="IFSC code"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="institution_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="institution name"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="last name"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="location",
            field=models.CharField(blank=True, max_length=50, verbose_name="location"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="middle_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="middle name"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="occupation",
            field=models.CharField(blank=True, max_length=50, verbose_name="occupation"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pan_number",
            field=models.CharField(blank=True, max_length=15, verbose_name="PAN number"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="permanent_address",
            field=models.TextField(blank=True, max_length=100, verbose_name="permanent address"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="place_of_institution",
            field=models.CharField(blank=True, max_length=50, verbose_name="place of institution"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="state_province",
            field=models.CharField(blank=True, max_length=50, verbose_name="state/province"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="work_experience",
            field=models.CharField(blank=True, max_length=2, verbose_name="work experience"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, max_length=1000, verbose_name="bio"),
        ),
    ]
