# Generated by Django 5.0.6 on 2026-07-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_psychometrician_assessment_perms'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cancellation_count',
            field=models.PositiveIntegerField(default=0, help_text='Tracks how often this counsellor cancels sessions (SRS §3.2)', verbose_name='cancellation count'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Counselling hourly rate in USD', max_digits=10, verbose_name='hourly rate'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_available_for_counseling',
            field=models.BooleanField(default=True, verbose_name='available for counseling'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='meeting_url',
            field=models.URLField(blank=True, default='', help_text='Default Zoom/Meet link for counselling sessions', verbose_name='meeting URL'),
        ),
    ]
