# Generated by Django 5.0.6 on 2026-08-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_counsellor_fields_on_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="geographical_location",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Counsellor: general geographical location/region",
                max_length=100,
                verbose_name="geographical location",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="language_of_communication",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Counsellor: languages spoken (e.g. 'English, Hindi')",
                max_length=100,
                verbose_name="language of communication",
            ),
        ),
        migrations.AlterField(
            model_name="moduleright",
            name="module",
            field=models.CharField(
                choices=[
                    ("accounts", "Accounts"),
                    ("organizations", "Organizations"),
                    ("question_bank", "Question Bank"),
                    ("assessment", "Assessment"),
                    ("career_profiling", "Career Profiling"),
                    ("reporting", "Reporting"),
                    ("training", "Training"),
                    ("counseling", "Counseling"),
                    ("cms", "CMS"),
                    ("notifications", "Notifications"),
                    ("tasks", "Task Management"),
                ],
                max_length=50,
                verbose_name="module",
            ),
        ),
    ]
