# Generated by Django 5.0.6 on 2026-09-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_psychometrician_reporting_perms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleright',
            name='module',
            field=models.CharField(choices=[('accounts', 'Accounts'), ('organizations', 'Organizations'), ('question_bank', 'Question Bank'), ('assessment', 'Assessment'), ('career_profiling', 'Career Profiling'), ('reporting', 'Reporting'), ('training', 'Training'), ('counseling', 'Counseling'), ('cms', 'CMS'), ('notifications', 'Notifications'), ('tasks', 'Task Management'), ('invoicing', 'Invoicing')], max_length=50, verbose_name='module'),
        ),
    ]
