# Generated by Django 5.0.6 on 2026-09-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_invoicing_module_rights'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='agency_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='agency name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allocated_region',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='allocated region'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manager_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='manager name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tan_number',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='TAN number'),
        ),
    ]
