# Generated by Django 5.0.6 on 2026-09-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userprofile_agency_name_userprofile_allocated_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='age'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='communicative_languages',
            field=models.JSONField(blank=True, default=list, verbose_name='communicative languages'),
        ),
    ]
