# Generated by Django 5.0.6 on 2026-10-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_sync_system_role_rights'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='domains_of_expertise',
            field=models.JSONField(blank=True, default=list, verbose_name='domains of expertise'),
        ),
    ]
