# Generated by Django 5.0.6 on 2026-07-24 22:33

import apps.tasks.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        default=apps.tasks.models._generate_task_id,
                        help_text="Human-readable unique ID like TSK-2026-AB12CD",
                        max_length=30,
                        unique=True,
                        verbose_name="task ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(
                        help_text="Task description / message", verbose_name="description"
                    ),
                ),
                (
                    "assignee_role",
                    models.CharField(
                        choices=[
                            ("sme", "SME"),
                            ("reviewer", "Reviewer"),
                            ("psychometrician", "Psychometrician"),
                            ("trainer", "Trainer"),
                            ("counsellor", "Counsellor"),
                        ],
                        max_length=20,
                        verbose_name="assignee role",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("awaiting_review", "Awaiting Admin Review"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("overdue", "Overdue"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="priority",
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True, verbose_name="due date")),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="started at"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="completed at"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="cancelled at"),
                ),
                (
                    "approval_comment",
                    models.TextField(blank=True, default="", verbose_name="approval comment"),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, default="", verbose_name="cancellation reason"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        help_text="Admin who assigned this task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        help_text="User the task is assigned to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        help_text="If this task builds on another (e.g. reviewer reviewing an SME task)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_tasks",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskExtensionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("current_due_date", models.DateTimeField(verbose_name="current due date")),
                ("requested_due_date", models.DateTimeField(verbose_name="requested due date")),
                ("reason", models.TextField(blank=True, default="", verbose_name="reason")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "review_comment",
                    models.TextField(blank=True, default="", verbose_name="review comment"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="reviewed at"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_extension_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_extension_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extension_requests",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "task extension request",
                "verbose_name_plural": "task extension requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskProgressUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "author_role",
                    models.CharField(
                        choices=[
                            ("assignee", "Assignee"),
                            ("admin", "Admin"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=20,
                        verbose_name="author role",
                    ),
                ),
                ("message", models.TextField(verbose_name="message")),
                (
                    "is_admin_request",
                    models.BooleanField(
                        default=False,
                        help_text="True if admin is requesting an update from assignee",
                        verbose_name="is admin request",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_progress_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_updates",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "task progress update",
                "verbose_name_plural": "task progress updates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "qb_category",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="QB category"
                    ),
                ),
                (
                    "qb_subcategory",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="QB subcategory"
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="question type"
                    ),
                ),
                (
                    "num_questions",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="number of questions"
                    ),
                ),
                (
                    "num_options",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="number of options"
                    ),
                ),
                (
                    "num_correct_options",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="number of correct options"
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                            ("expert", "Expert"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="difficulty level",
                    ),
                ),
                (
                    "cognitive_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("remember", "Remember"),
                            ("understand", "Understand"),
                            ("apply", "Apply"),
                            ("analyze", "Analyze"),
                            ("evaluate", "Evaluate"),
                            ("create", "Create"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="cognitive level",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spec",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "task spec",
                "verbose_name_plural": "task specs",
            },
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assigned_to", "status"], name="tasks_task_assigne_b3b2bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assigned_by", "status"], name="tasks_task_assigne_2183bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["status", "due_date"], name="tasks_task_status_0eabcf_idx"),
        ),
    ]
