# Generated by Django 5.0.6 on 2026-09-11 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20, verbose_name='status')),
                ('resolution_comment', models.TextField(blank=True, default='', verbose_name='resolution comment')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerns_raised', to=settings.AUTH_USER_MODEL)),
                ('related_task', models.ForeignKey(blank=True, help_text='Optional: the task this concern is about, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concerns', to='tasks.task')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concerns_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'concern',
                'verbose_name_plural': 'concerns',
                'ordering': ['-created_at'],
            },
        ),
    ]
