# Generated by Django 5.0.6 on 2026-09-11 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_concern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskspec',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='tasks.task'),
        ),
    ]
