# Generated by Django 5.0.6 on 2026-10-02 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_taskspec_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='SME tasks: the Reviewer the SME sends the completed questions to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_as_designated_reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
