# Generated by Django 5.0.6 on 2026-07-24 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_provider', models.CharField(choices=[('stripe', 'Stripe'), ('razorpay', 'Razorpay'), ('manual', 'Manual (no gateway)')], default='manual', max_length=20, verbose_name='active provider')),
                ('stripe_secret_key', models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe secret key')),
                ('stripe_publishable_key', models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe publishable key')),
                ('stripe_webhook_secret', models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe webhook secret')),
                ('razorpay_key_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Razorpay key ID')),
                ('razorpay_key_secret', models.CharField(blank=True, default='', max_length=255, verbose_name='Razorpay key secret')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('is_active', models.BooleanField(default=False, verbose_name='payments enabled')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'payment settings',
                'verbose_name_plural': 'payment settings',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('training', 'Training Course'), ('counseling', 'Counseling Session'), ('assessment', 'Assessment'), ('reporting', 'Report')], max_length=20, verbose_name='module')),
                ('item_id', models.PositiveIntegerField(help_text='The ID of the item being paid for', verbose_name='item ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('pending', 'Pending (awaiting payment)'), ('paid', 'Paid'), ('failed', 'Payment Failed'), ('refunded', 'Refunded'), ('free', 'Free (no payment required)')], default='pending', max_length=20, verbose_name='status')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('razorpay', 'Razorpay'), ('manual', 'Manual (offline)'), ('free', 'Free')], default='stripe', max_length=20, verbose_name='provider')),
                ('provider_session_id', models.CharField(blank=True, default='', max_length=255, verbose_name='provider session ID')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'module', 'item_id')},
            },
        ),
    ]
