# Generated by Django 5.0.6 on 2026-07-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='paytm_merchant_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Paytm merchant ID'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='paytm_merchant_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Paytm merchant key'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='razorpay_webhook_secret',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Razorpay webhook secret'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('razorpay', 'Razorpay (Primary)'), ('stripe', 'Stripe (Optional)'), ('paytm', 'Paytm (Optional)'), ('manual', 'Manual (no gateway)'), ('free', 'Free')], default='stripe', max_length=20, verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='active_provider',
            field=models.CharField(choices=[('razorpay', 'Razorpay (Primary)'), ('stripe', 'Stripe (Optional)'), ('paytm', 'Paytm (Optional)'), ('manual', 'Manual (no gateway)')], default='razorpay', max_length=20, verbose_name='active provider'),
        ),
    ]
