# Generated by Django 5.0.6 on 2026-09-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_razorpay_paytm'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='refunded at'),
        ),
    ]
