# Generated by Django 5.0.6 on 2026-07-11 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("question_bank", "0008_alter_hotspotarea_options_alter_hotspotarea_x_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("objective", models.TextField(blank=True, verbose_name="objective")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("instructions", models.TextField(blank=True, verbose_name="instructions")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft (being configured)"),
                            ("published", "Published (available for sessions)"),
                            ("archived", "Archived (no new sessions)"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "total_duration_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total time for the assessment. NULL = no time limit.",
                        null=True,
                        verbose_name="total duration (seconds)",
                    ),
                ),
                (
                    "timer_level",
                    models.CharField(
                        choices=[
                            ("assessment", "Assessment Level (Level 0)"),
                            ("level1", "Level 1 (Section)"),
                            ("level2", "Level 2 (Sub-section)"),
                            ("level3", "Level 3"),
                            ("level4", "Level 4"),
                            ("question", "Question Level"),
                        ],
                        default="assessment",
                        help_text="Level at which the timer operates. Only ONE level can have a timer.",
                        max_length=20,
                        verbose_name="timer level",
                    ),
                ),
                (
                    "display_order",
                    models.CharField(
                        choices=[("RANDOM", "Random"), ("STATIC", "Static (as configured)")],
                        default="STATIC",
                        max_length=10,
                        verbose_name="display order",
                    ),
                ),
                (
                    "navigation_rule",
                    models.CharField(
                        choices=[
                            ("FREE", "Free Navigation and Response Review"),
                            ("PREV_SECTION", "Only Previous Section Backward Navigation"),
                            (
                                "NO_BACKWARD_SECTION",
                                "No Backward/Forward Navigation (Section Level)",
                            ),
                            (
                                "NO_BACKWARD_QUESTION",
                                "No Backward/Forward Navigation (Question Level)",
                            ),
                        ],
                        default="FREE",
                        max_length=30,
                        verbose_name="navigation rule",
                    ),
                ),
                (
                    "attempt_rule",
                    models.CharField(
                        choices=[
                            ("MULTIPLE_RETAKE", "Multiple Retakes Allowed"),
                            ("SINGLE_RETAKE", "Multiple Retakes Not Allowed"),
                            ("MULTIPLE_SESSION", "Multiple Sessions Allowed"),
                            ("SINGLE_SESSION", "Multiple Sessions Not Allowed"),
                        ],
                        default="SINGLE_SESSION",
                        max_length=20,
                        verbose_name="attempt rule",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "assessment",
                "verbose_name_plural": "assessments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "level",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="1-4. Level 1 = top-level variable, Level 4 = deepest sub-variable.",
                        verbose_name="level",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Time for this section. Only used if timer_level matches this level.",
                        null=True,
                        verbose_name="duration (seconds)",
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="assessment.assessment",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent section. NULL = top-level (Level 1).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsections",
                        to="assessment.assessmentsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "assessment section",
                "verbose_name_plural": "assessment sections",
                "ordering": ["level", "order"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active (in progress)"),
                            ("suspended", "Suspended (can resume)"),
                            ("completed", "Completed (submitted)"),
                            ("abandoned", "Abandoned (timed out or force-quit)"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "suspended_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="suspended at"),
                ),
                (
                    "resumed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="resumed at"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="completed at"),
                ),
                (
                    "total_score",
                    models.FloatField(blank=True, null=True, verbose_name="total score"),
                ),
                ("max_score", models.FloatField(blank=True, null=True, verbose_name="max score")),
                ("percentage", models.FloatField(blank=True, null=True, verbose_name="percentage")),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="assessment.assessment",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "assessment session",
                "verbose_name_plural": "assessment sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "sub_question_index",
                    models.PositiveIntegerField(default=0, verbose_name="sub-question index"),
                ),
                (
                    "score_override",
                    models.FloatField(
                        blank=True,
                        help_text="Override the default max score for this question in this assessment.",
                        null=True,
                        verbose_name="score override",
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Per-question timer. Only used if timer_level='question'.",
                        null=True,
                        verbose_name="duration (seconds)",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_assignments",
                        to="question_bank.question",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="assessment.assessmentsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "assessment question",
                "verbose_name_plural": "assessment questions",
                "ordering": ["order"],
                "unique_together": {("section", "question", "sub_question_index")},
            },
        ),
        migrations.CreateModel(
            name="QuestionAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sub_question_index",
                    models.PositiveIntegerField(default=0, verbose_name="sub-question index"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_attempted", "Not Attempted"),
                            ("attempted", "Attempted"),
                            ("bookmarked", "Bookmarked (for review)"),
                            ("skipped", "Skipped"),
                        ],
                        default="not_attempted",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "raw_answer",
                    models.JSONField(
                        blank=True,
                        help_text="Flexible JSON storage for all answer types.",
                        null=True,
                        verbose_name="raw answer",
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True, verbose_name="score")),
                ("max_score", models.FloatField(blank=True, null=True, verbose_name="max score")),
                (
                    "answered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="answered at"),
                ),
                (
                    "time_spent_seconds",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="time spent (seconds)"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="question_bank.question",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_attempts",
                        to="assessment.assessmentsection",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_attempts",
                        to="assessment.assessmentsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "question attempt",
                "verbose_name_plural": "question attempts",
                "ordering": ["section__order", "question__created_at"],
                "unique_together": {("session", "question", "sub_question_index")},
            },
        ),
        migrations.CreateModel(
            name="SectionScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("raw_score", models.FloatField(default=0, verbose_name="raw score")),
                ("max_score", models.FloatField(default=0, verbose_name="max score")),
                ("percentage", models.FloatField(blank=True, null=True, verbose_name="percentage")),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="assessment.assessmentsection",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_scores",
                        to="assessment.assessmentsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "section score",
                "verbose_name_plural": "section scores",
                "ordering": ["section__level", "section__order"],
                "unique_together": {("session", "section")},
            },
        ),
    ]
