# Generated by Django 5.0.6 on 2026-07-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="assessment_type",
            field=models.CharField(
                choices=[
                    (
                        "normal",
                        "Normal Assessment (aptitude/ability — MCQ, FITB, Match, Grid, Hotspot)",
                    ),
                    (
                        "psychometric",
                        "Psychometric Assessment (Rating, Rank, Rank-then-Rate, Forced-Choice)",
                    ),
                ],
                default="normal",
                help_text="Determines which question categories can be attached. Normal assessments accept only normal questions (MCQ/FITB/Match/Grid/Hotspot); psychometric assessments accept only psychometric questions (Rating/Rank/Rank-then-Rate/Forced-Choice). Mixing is not allowed.",
                max_length=20,
                verbose_name="assessment type",
            ),
        ),
    ]
