# Generated by Django 5.0.6 on 2026-09-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_assessmentmodificationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsection',
            name='delivery_count',
            field=models.PositiveIntegerField(blank=True, help_text='SRS §4.1.1 — number of assigned questions to actually present during delivery. Set on the last-level (leaf) variable that holds questions. If set and less than the assigned count, that many questions are selected at random per session. NULL (or >= assigned count) delivers all.', null=True, verbose_name='delivery count'),
        ),
    ]
