# Generated by Django 5.0.6 on 2026-09-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0004_assessmentsection_delivery_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentsection",
            name="order_mode",
            field=models.CharField(
                choices=[("STATIC", "Static (as configured)"), ("RANDOM", "Random")],
                default="STATIC",
                help_text="ASM-5 / §5.1: delivery order of this section's questions — STATIC keeps the configured order; RANDOM shuffles them per session (per-level ordering).",
                max_length=10,
                verbose_name="order mode",
            ),
        ),
    ]
