# Generated by Django 5.0.6 on 2026-09-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_assessmentsection_order_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price to attempt this assessment. 0 = free (no payment gate).', max_digits=10, verbose_name='price'),
        ),
    ]
