# Generated by Django 5.0.6 on 2026-09-18 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_assessment_price'),
        ('question_bank', '0019_alter_question_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychometricGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(choices=[('rank_simple', 'Simple Ranking (6a)'), ('rank_then_rate', 'Rank then Rate (6b)'), ('forced_choice_single', 'Forced Choice - Single Level (8a)'), ('forced_choice_two_level', 'Forced Choice - Two Level (8b)')], max_length=30, verbose_name='group type')),
                ('group_number', models.PositiveIntegerField(default=1, verbose_name='group number')),
                ('rating_scale_points', models.PositiveIntegerField(blank=True, null=True, verbose_name='rating scale points')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychometric_groups', to='assessment.assessment')),
            ],
            options={
                'verbose_name': 'psychometric group',
                'verbose_name_plural': 'psychometric groups',
                'ordering': ['order', 'group_number'],
            },
        ),
        migrations.CreateModel(
            name='PsychometricGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assessment.psychometricgroup')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychometric_group_items', to='assessment.assessmentsection')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychometric_group_items', to='question_bank.question')),
            ],
            options={
                'verbose_name': 'psychometric group item',
                'verbose_name_plural': 'psychometric group items',
                'ordering': ['order'],
                'unique_together': {('group', 'statement')},
            },
        ),
    ]
