# Generated by Django 5.0.6 on 2026-09-18 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_psychometricgroup_psychometricgroupitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychometricGroupResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_attempted', 'Not Attempted'), ('attempted', 'Attempted'), ('skipped', 'Skipped')], default='not_attempted', max_length=20, verbose_name='status')),
                ('raw_answer', models.JSONField(blank=True, null=True, verbose_name='raw answer')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='answered at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessment.psychometricgroup')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_responses', to='assessment.assessmentsession')),
            ],
            options={
                'verbose_name': 'psychometric group response',
                'verbose_name_plural': 'psychometric group responses',
                'unique_together': {('session', 'group')},
            },
        ),
    ]
