# Generated by Django 5.0.6 on 2026-09-29 11:46

from collections import defaultdict

from django.db import migrations


def renumber_orders(apps, schema_editor):
    """Give every sibling group a distinct 1..n `order`, keeping any explicit
    ordering and breaking ties by creation (id). Sections and assigned
    questions were all created with order=0, so their "configured order" was
    whatever the database returned for the tie (Report 7 #1/#4/#12/#34)."""
    AssessmentSection = apps.get_model("assessment", "AssessmentSection")
    AssessmentQuestion = apps.get_model("assessment", "AssessmentQuestion")

    groups = defaultdict(list)
    for s in AssessmentSection.objects.all().only("id", "assessment_id", "parent_id", "order"):
        groups[(s.assessment_id, s.parent_id)].append(s)
    for sibs in groups.values():
        for i, s in enumerate(sorted(sibs, key=lambda x: (x.order, x.id)), start=1):
            if s.order != i:
                s.order = i
                s.save(update_fields=["order"])

    groups = defaultdict(list)
    for q in AssessmentQuestion.objects.all().only("id", "section_id", "order"):
        groups[q.section_id].append(q)
    for sibs in groups.values():
        for i, q in enumerate(sorted(sibs, key=lambda x: (x.order, x.id)), start=1):
            if q.order != i:
                q.order = i
                q.save(update_fields=["order"])


def rehome_sub_question_attempts(apps, schema_editor):
    """Sub-question answer rows were created under `sections.first()` instead
    of their question's section — move them to the anchor row's section so
    existing sessions show the right sidebar and score to the right section."""
    QuestionAttempt = apps.get_model("assessment", "QuestionAttempt")
    anchors = {}
    for a in QuestionAttempt.objects.order_by("sub_question_index", "id").only(
        "id", "session_id", "question_id", "section_id", "sub_question_index"
    ):
        key = (a.session_id, a.question_id)
        if key not in anchors:
            anchors[key] = a.section_id
        elif a.sub_question_index > 0 and a.section_id != anchors[key]:
            a.section_id = anchors[key]
            a.save(update_fields=["section"])


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0008_psychometricgroupresponse"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assessmentquestion",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "assessment question",
                "verbose_name_plural": "assessment questions",
            },
        ),
        migrations.AlterModelOptions(
            name="assessmentsection",
            options={
                "ordering": ["level", "order", "id"],
                "verbose_name": "assessment section",
                "verbose_name_plural": "assessment sections",
            },
        ),
        migrations.RunPython(renumber_orders, migrations.RunPython.noop),
        migrations.RunPython(rehome_sub_question_attempts, migrations.RunPython.noop),
    ]
