# Generated by Django 5.0.6 on 2026-09-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_delivery_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychometricgroup',
            name='question_text_1',
            field=models.TextField(blank=True, default='', verbose_name='question text 1'),
        ),
        migrations.AddField(
            model_name='psychometricgroup',
            name='question_text_2',
            field=models.TextField(blank=True, default='', verbose_name='question text 2'),
        ),
        migrations.AddField(
            model_name='psychometricgroup',
            name='question_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='question title'),
        ),
    ]
