# Generated by Django 5.0.6 on 2026-10-02 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_psychometric_group_texts'),
        ('organizations', '0008_organization_enabled_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='owner_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_assessments', to='organizations.organization'),
        ),
    ]
