# Generated by Django 5.0.6 on 2026-07-02 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category. NULL = top-level category.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="question_bank.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("MCQ_TEXT_IMAGE", "1a: MCQ – Text/Image"),
                            (
                                "MCQ_TEXT_IMAGE_IMG_OPTIONS",
                                "1b: MCQ – Text/Image with Image Options",
                            ),
                            ("MCQ_AUDIO_MULTI", "1c: MCQ – Audio with Multiple Questions"),
                            ("MCQ_VIDEO_MULTI", "1d: MCQ – Video with Multiple Questions"),
                            (
                                "MCQ_WORD_FLASH_MULTI",
                                "1e: MCQ – Word Flash with Multiple Questions",
                            ),
                            (
                                "MCQ_IMAGE_FLASH_MULTI",
                                "1f: MCQ – Image Flash with Multiple Questions",
                            ),
                            (
                                "MCQ_PASSAGE_DISPLAY_MULTI",
                                "1g: MCQ – Passage Display with Multiple Questions",
                            ),
                            (
                                "MCQ_IMAGE_DISPLAY_MULTI",
                                "1h: MCQ – Image Display with Multiple Questions",
                            ),
                            ("FITB_SINGLE", "2a: FITB – Single Field"),
                            ("FITB_MULTI_FIELD", "2b: FITB – Multiple Fields"),
                            (
                                "FITB_WORD_FLASH_MULTI",
                                "2c: FITB – Word Flash with Multiple Recall Fields",
                            ),
                            (
                                "FITB_IMAGE_FLASH_MULTI",
                                "2d: FITB – Image Flash with Multiple Recall Fields",
                            ),
                            ("MATCH_FOLLOWING", "3: Match-the-Following"),
                            ("GRID_LIST_SELECTION", "4: Grid-List Selection"),
                            ("HOTSPOT_SINGLE", "5a: Hotspot – Single Answer"),
                            ("HOTSPOT_MULTI", "5b: Hotspot – Multiple Answers"),
                            ("RANK_SIMPLE", "6a: Simple Ranking Scale"),
                            ("RANK_THEN_RATE", "6b: First Rank-Then Rate Scale"),
                            ("STANDARD_RATING_SCALE", "7: Standard Rating Scale"),
                            ("FORCED_CHOICE_SINGLE_LEVEL", "8a: Forced-Choice – Single Level"),
                            ("FORCED_CHOICE_TWO_LEVEL", "8b: Forced-Choice – Two-Level"),
                        ],
                        max_length=50,
                        verbose_name="question type",
                    ),
                ),
                (
                    "question_id_label",
                    models.CharField(
                        blank=True,
                        help_text="Display ID shown to candidate",
                        max_length=50,
                        verbose_name="question ID label",
                    ),
                ),
                ("question_text_1", models.TextField(verbose_name="question text 1")),
                ("question_text_2", models.TextField(blank=True, verbose_name="question text 2")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="questions/images/", verbose_name="image"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "scoring_type",
                    models.CharField(
                        choices=[
                            ("BINARY", "Binary Scoring (0 or 1)"),
                            ("BINARY_FUZZY", "Binary with Fuzzy/Percentage Match"),
                            ("PARTIAL", "Partial Credit Scoring"),
                            ("NEGATIVE", "Negative Marking"),
                            ("RANK", "Rank Scoring"),
                            ("RANK_RATE", "Rank-then-Rate Scoring"),
                            ("RATING", "Rating Scale Scoring"),
                            ("FORCED_CHOICE", "Forced-Choice Scoring"),
                            ("FORCED_CHOICE_RATED", "Forced-Choice Two-Level Scoring"),
                        ],
                        default="BINARY",
                        max_length=30,
                        verbose_name="scoring type",
                    ),
                ),
                (
                    "case_sensitive",
                    models.BooleanField(
                        default=False, help_text="For FITB types", verbose_name="case sensitive"
                    ),
                ),
                (
                    "pct_match_threshold",
                    models.FloatField(
                        blank=True,
                        help_text="For FITB fuzzy match (0-100)",
                        null=True,
                        verbose_name="percentage match threshold",
                    ),
                ),
                (
                    "display_duration_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="For timed display types 1g/1h",
                        null=True,
                        verbose_name="display duration (seconds)",
                    ),
                ),
                (
                    "flash_interval_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="For flash types 1e/1f/2c/2d",
                        null=True,
                        verbose_name="flash interval (ms)",
                    ),
                ),
                (
                    "flash_display_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="flash display count"
                    ),
                ),
                (
                    "grid_rows",
                    models.PositiveIntegerField(
                        blank=True, help_text="For type 4", null=True, verbose_name="grid rows"
                    ),
                ),
                (
                    "grid_cols",
                    models.PositiveIntegerField(
                        blank=True, help_text="For type 4", null=True, verbose_name="grid columns"
                    ),
                ),
                (
                    "rating_scale_points",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="For types 6b/7/8b",
                        null=True,
                        verbose_name="rating scale points",
                    ),
                ),
                (
                    "rating_direction",
                    models.CharField(
                        blank=True,
                        choices=[("FORWARD", "Forward"), ("REVERSE", "Reverse")],
                        max_length=10,
                        null=True,
                        verbose_name="rating direction",
                    ),
                ),
                (
                    "passage_title",
                    models.CharField(
                        blank=True,
                        help_text="For type 1g",
                        max_length=255,
                        verbose_name="passage title",
                    ),
                ),
                (
                    "passage_body",
                    models.TextField(
                        blank=True, help_text="For type 1g", verbose_name="passage body"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft (SME editing)"),
                            ("pending_content_review", "Pending Content Review (Reviewer)"),
                            ("content_reviewed", "Content Reviewed (Approved by Reviewer)"),
                            (
                                "pending_psychometric_review",
                                "Pending Psychometric Review (Psychometrician)",
                            ),
                            ("confirmed", "Confirmed (Added to Question Bank)"),
                            ("sent_back", "Sent Back (Needs revision)"),
                            ("rejected", "Rejected"),
                            ("inactive", "Inactive"),
                        ],
                        default="draft",
                        max_length=50,
                        verbose_name="status",
                    ),
                ),
                (
                    "exposure_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Max times question can be used before auto-deactivation (set by Psychometrician)",
                        null=True,
                        verbose_name="exposure limit",
                    ),
                ),
                (
                    "exposure_count",
                    models.PositiveIntegerField(default=0, verbose_name="exposure count"),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        blank=True,
                        help_text="E.g., Easy, Medium, Hard",
                        max_length=20,
                        verbose_name="difficulty level",
                    ),
                ),
                (
                    "cognitive_level",
                    models.CharField(
                        blank=True,
                        help_text="E.g., Recall, Understanding, Application, Analysis",
                        max_length=50,
                        verbose_name="cognitive level",
                    ),
                ),
                (
                    "discrimination_index",
                    models.FloatField(
                        blank=True,
                        help_text="How well the question discriminates between high/low performers (-1 to 1)",
                        null=True,
                        verbose_name="discrimination index",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="question_bank.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "question",
                "verbose_name_plural": "questions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("AUDIO", "Audio"), ("VIDEO", "Video")],
                        max_length=10,
                        verbose_name="media type",
                    ),
                ),
                ("file", models.FileField(upload_to="questions/media/", verbose_name="file")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="question_bank.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "media file",
                "verbose_name_plural": "media files",
            },
        ),
        migrations.CreateModel(
            name="HotspotArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sub_question_index",
                    models.PositiveIntegerField(default=0, verbose_name="sub-question index"),
                ),
                (
                    "x",
                    models.PositiveIntegerField(
                        help_text="Top-left x pixel coordinate", verbose_name="x"
                    ),
                ),
                (
                    "y",
                    models.PositiveIntegerField(
                        help_text="Top-left y pixel coordinate", verbose_name="y"
                    ),
                ),
                ("width_px", models.PositiveIntegerField(verbose_name="width (px)")),
                ("height_px", models.PositiveIntegerField(verbose_name="height (px)")),
                (
                    "area_size_code",
                    models.CharField(blank=True, max_length=10, verbose_name="area size code"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotspot_areas",
                        to="question_bank.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "hotspot area",
                "verbose_name_plural": "hotspot areas",
                "ordering": ["sub_question_index"],
            },
        ),
        migrations.CreateModel(
            name="FlashItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("TEXT", "Text"), ("IMAGE", "Image")],
                        max_length=10,
                        verbose_name="item type",
                    ),
                ),
                (
                    "text_value",
                    models.CharField(blank=True, max_length=255, verbose_name="text value"),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="questions/flash/",
                        verbose_name="image file",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "is_in_display_pool",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this item can be randomly selected for display",
                        verbose_name="in display pool",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flash_items",
                        to="question_bank.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "flash item",
                "verbose_name_plural": "flash items",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuestionReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("content", "Content Review (Reviewer)"),
                            ("psychometric", "Psychometric Review (Psychometrician)"),
                        ],
                        max_length=20,
                        verbose_name="review type",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("send_back", "Send Back to Previous Stage"),
                            ("reject", "Reject"),
                        ],
                        max_length=20,
                        verbose_name="action",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Feedback/reason for the action",
                        verbose_name="comment",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="1-5 scale (set by reviewer/psychometrician)",
                        null=True,
                        verbose_name="content quality rating",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="question_bank.question",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="question_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "question review",
                "verbose_name_plural": "question reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResponseOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sub_question_index",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="For multi-sub-question types; 0 = main question",
                        verbose_name="sub-question index",
                    ),
                ),
                (
                    "option_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text Option"),
                            ("IMAGE", "Image Option"),
                            ("MATCH_A", "Match Group A Item"),
                            ("MATCH_B", "Match Group B Item"),
                            ("DRAG_POOL", "Drag Pool Item (Grid)"),
                            ("RANK", "Rank Item"),
                            ("FORCED_CHOICE", "Forced-Choice Item"),
                        ],
                        default="TEXT",
                        max_length=20,
                        verbose_name="option type",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Option 1, Group A item 3",
                        max_length=100,
                        verbose_name="label",
                    ),
                ),
                ("text_value", models.TextField(blank=True, verbose_name="text value")),
                (
                    "image_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="questions/options/",
                        verbose_name="image file",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False,
                        help_text="For MCQ, grid, hotspot etc.",
                        verbose_name="is correct",
                    ),
                ),
                (
                    "match_pair_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="For match-the-following: links Group A item to correct Group B item",
                        null=True,
                        verbose_name="match pair ID",
                    ),
                ),
                (
                    "predefined_score",
                    models.FloatField(
                        default=1.0,
                        help_text="For forced-choice: may be 0,1,2,3 etc.",
                        verbose_name="predefined score",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="question_bank.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "response option",
                "verbose_name_plural": "response options",
                "ordering": ["sub_question_index", "order"],
            },
        ),
        migrations.CreateModel(
            name="CorrectAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("answer_text", models.CharField(max_length=500, verbose_name="answer text")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "response_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correct_answers",
                        to="question_bank.responseoption",
                    ),
                ),
            ],
            options={
                "verbose_name": "correct answer",
                "verbose_name_plural": "correct answers",
                "ordering": ["order"],
            },
        ),
    ]
