# Generated by Django 5.0.6 on 2026-07-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_bank", "0007_question_image_dimensions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hotspotarea",
            options={
                "ordering": ["sub_question_index", "id"],
                "verbose_name": "hotspot area",
                "verbose_name_plural": "hotspot areas",
            },
        ),
        migrations.AlterField(
            model_name="hotspotarea",
            name="x",
            field=models.PositiveIntegerField(
                help_text="Top-left x (rect) or center x (circle)", verbose_name="x"
            ),
        ),
        migrations.AlterField(
            model_name="hotspotarea",
            name="y",
            field=models.PositiveIntegerField(
                help_text="Top-left y (rect) or center y (circle)", verbose_name="y"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("MCQ_TEXT_IMAGE", "1a: MCQ - Text/Image"),
                    ("MCQ_TEXT_IMAGE_IMG_OPTIONS", "1b: MCQ - Text/Image with Image Options"),
                    ("MCQ_AUDIO_MULTI", "1c: MCQ - Audio with Multiple Questions"),
                    ("MCQ_VIDEO_MULTI", "1d: MCQ - Video with Multiple Questions"),
                    ("MCQ_WORD_FLASH_MULTI", "1e: MCQ - Word Flash with Multiple Questions"),
                    ("MCQ_IMAGE_FLASH_MULTI", "1f: MCQ - Image Flash with Multiple Questions"),
                    (
                        "MCQ_PASSAGE_DISPLAY_MULTI",
                        "1g: MCQ - Passage Display with Multiple Questions",
                    ),
                    ("MCQ_IMAGE_DISPLAY_MULTI", "1h: MCQ - Image Display with Multiple Questions"),
                    ("FITB_SINGLE", "2a: FITB - Single Field"),
                    ("FITB_MULTI_FIELD", "2b: FITB - Multiple Fields"),
                    ("FITB_WORD_FLASH_MULTI", "2c: FITB - Word Flash with Multiple Recall Fields"),
                    (
                        "FITB_IMAGE_FLASH_MULTI",
                        "2d: FITB - Image Flash with Multiple Recall Fields",
                    ),
                    ("MATCH_FOLLOWING", "3: Match-the-Following"),
                    ("GRID_LIST_SELECTION", "4: Grid-List Selection"),
                    ("HOTSPOT_SINGLE", "5a: Hotspot - Single Answer"),
                    ("HOTSPOT_MULTI", "5b: Hotspot - Multiple Answers"),
                    ("RANK_SIMPLE", "6a: Simple Ranking Scale"),
                    ("RANK_THEN_RATE", "6b: First Rank-Then Rate Scale"),
                    ("STANDARD_RATING_SCALE", "7: Standard Rating Scale"),
                    ("FORCED_CHOICE_SINGLE_LEVEL", "8a: Forced-Choice - Single Level"),
                    ("FORCED_CHOICE_TWO_LEVEL", "8b: Forced-Choice - Two-Level"),
                ],
                max_length=50,
                verbose_name="question type",
            ),
        ),
    ]
