# Generated by Django 5.0.6 on 2026-07-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0008_alter_hotspotarea_options_alter_hotspotarea_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='bottom_group_difficulty_index',
            field=models.FloatField(blank=True, help_text='Bottom-27% group Item Difficulty Index (0-1). Computed by psychometric analysis.', null=True, verbose_name='bottom-group difficulty index (BDI)'),
        ),
        migrations.AddField(
            model_name='question',
            name='difference_difficulty_index',
            field=models.FloatField(blank=True, help_text='TDI - BDI. Positive = good discrimination. Computed by psychometric analysis.', null=True, verbose_name='difference difficulty index (DDI)'),
        ),
        migrations.AddField(
            model_name='question',
            name='item_difficulty_index',
            field=models.FloatField(blank=True, help_text='Total-group Item Difficulty Index (0-1). Computed by psychometric analysis.', null=True, verbose_name='item difficulty index (IDI)'),
        ),
        migrations.AddField(
            model_name='question',
            name='item_total_correlation',
            field=models.FloatField(blank=True, help_text='Item-Total Correlation Index for non-MCQ questions (-1 to 1). Computed by psychometric analysis.', null=True, verbose_name='item total correlation'),
        ),
        migrations.AddField(
            model_name='question',
            name='psychometric_analyzed_at',
            field=models.DateTimeField(blank=True, help_text='When psychometric analysis was last run on this question.', null=True, verbose_name='psychometric analyzed at'),
        ),
        migrations.AddField(
            model_name='question',
            name='top_group_difficulty_index',
            field=models.FloatField(blank=True, help_text='Top-27% group Item Difficulty Index (0-1). Computed by psychometric analysis.', null=True, verbose_name='top-group difficulty index (TDI)'),
        ),
    ]
