# Generated by Django 5.0.6 on 2026-07-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0009_psychometric_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='display_mode',
            field=models.CharField(choices=[('timed', 'Timed Display (no replay after expiry)'), ('unlimited', 'Unlimited Display (stays until next question)')], default='unlimited', help_text='For passage/image display: timed = expires after display_duration_seconds, unlimited = stays visible until test taker moves on', max_length=10, verbose_name='display mode'),
        ),
        migrations.AddField(
            model_name='question',
            name='hotspot_visibility',
            field=models.CharField(choices=[('transparent', 'Transparent (spot-marking not visible to test taker)'), ('visible', 'Visible (spot-marking shown to test taker)')], default='transparent', help_text='For hotspot questions: whether the hotspot areas are visible to the test taker', max_length=12, verbose_name='hotspot visibility'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_layout',
            field=models.CharField(choices=[('1', 'Single Column (default)'), ('2', 'Two Columns'), ('3', 'Three Columns')], default='1', help_text='How answer options are arranged in the assessment player', max_length=1, verbose_name='option layout'),
        ),
        migrations.AddField(
            model_name='question',
            name='replay_mode',
            field=models.CharField(choices=[('permitted', 'Replay Permitted (test taker can replay audio/video)'), ('not_permitted', 'Replay Not Permitted (one-time playback only)')], default='not_permitted', help_text='For audio/video/flash: whether the test taker can replay the content', max_length=15, verbose_name='replay mode'),
        ),
    ]
