# Generated by Django 5.0.6 on 2026-07-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_bank", "0010_feedback_report_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="sub_question_count",
            field=models.PositiveIntegerField(
                default=1,
                help_text="For multi-sub-question types 1c-1h: how many sub-questions share the media. 1 = single question (default). Each sub-question has its own Question Text 2 + options.",
                verbose_name="sub-question count",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="sub_question_text_2_list",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="JSON list of Question Text 2 strings, one per sub-question. Index 0 = sub-question 1, etc. Empty list = use the single question_text_2 field for all sub-questions.",
                verbose_name="sub-question text 2 list",
            ),
        ),
        migrations.AlterField(
            model_name="responseoption",
            name="option_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text Option"),
                    ("IMAGE", "Image Option"),
                    ("MATCH_A", "Match Group A Item"),
                    ("MATCH_B", "Match Group B Item"),
                    ("MATCH_DUMMY", "Match Dummy (Non-matching) Item"),
                    ("DRAG_POOL", "Drag Pool Item (Grid)"),
                    ("RANK", "Rank Item"),
                    ("FORCED_CHOICE", "Forced-Choice Item"),
                ],
                default="TEXT",
                max_length=20,
                verbose_name="option type",
            ),
        ),
    ]
