# Generated by Django 5.0.6 on 2026-07-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_bank", "0011_question_sub_question_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="sub_question_texts",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="JSON list of sub-question text strings, one per sub-question. Index 0 = sub-question 1, etc. Each sub-question shows this text before its options. This is separate from question_text_2 (the main question's secondary text shown after the media).",
                verbose_name="sub-question texts",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="sub_question_count",
            field=models.PositiveIntegerField(
                default=1,
                help_text="For multi-sub-question types 1c-1h: how many sub-questions share the media. 1 = single question (default). Each sub-question has its own sub_question_text + options.",
                verbose_name="sub-question count",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="sub_question_text_2_list",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Deprecated. Use sub_question_texts instead.",
                verbose_name="sub-question text 2 list (deprecated)",
            ),
        ),
    ]
