# Generated by Django 5.0.6 on 2026-08-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_bank", "0012_question_sub_question_texts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="responseoption",
            name="non_selection_score",
            field=models.FloatField(
                default=0.0,
                help_text="Forced-Choice: score when this option is NOT selected. Must be < selection_score.",
                verbose_name="non-selection score",
            ),
        ),
        migrations.AddField(
            model_name="responseoption",
            name="section_tag",
            field=models.CharField(
                blank=True,
                default="",
                help_text="For psychometric question types (Rank, RankRate, ForcedChoice): the section this option belongs to. Each option in a rank/forced-choice question is tagged to a different section.",
                max_length=100,
                verbose_name="section tag",
            ),
        ),
        migrations.AddField(
            model_name="responseoption",
            name="selection_score",
            field=models.FloatField(
                default=1.0,
                help_text="Forced-Choice: score when this option is selected. Must be > non_selection_score.",
                verbose_name="selection score",
            ),
        ),
    ]
