# Generated by Django 5.0.6 on 2026-08-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0013_responseoption_non_selection_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseoption',
            name='predefined_score',
            field=models.FloatField(default=1.0, help_text='Deprecated for forced-choice (kept for backward-compat). Use selection_score / non_selection_score instead.', verbose_name='predefined score'),
        ),
    ]
