# Generated by Django 5.0.6 on 2026-09-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0014_alter_responseoption_predefined_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseoption',
            name='non_selection_score',
            field=models.FloatField(default=0.0, help_text="Forced-choice: score posted to this option's section when the candidate does NOT select it. Must be >= 0 and < selection_score. Default 0.", verbose_name='non-selection score'),
        ),
        migrations.AlterField(
            model_name='responseoption',
            name='section_tag',
            field=models.CharField(blank=True, default='', help_text="Psychometric types: the profile variable / section this option feeds into (e.g. 'Leadership'). Resolved to an AssessmentSection when the question is attached to an assessment.", max_length=100, verbose_name='section tag'),
        ),
        migrations.AlterField(
            model_name='responseoption',
            name='selection_score',
            field=models.FloatField(default=1.0, help_text="Forced-choice: score posted to this option's section when the candidate SELECTS it. Rule: selection_score > non_selection_score >= 0. Default 1.", verbose_name='selection score'),
        ),
    ]
