# Generated by Django 5.0.6 on 2026-09-11 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0015_alter_responseoption_non_selection_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBankDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('category', 'Category'), ('question', 'Question')], max_length=10, verbose_name='target type')),
                ('target_id', models.PositiveIntegerField(verbose_name='target ID')),
                ('target_label', models.CharField(blank=True, default='', help_text="Snapshot of the target's name/title, kept for the audit trail.", max_length=255, verbose_name='target label')),
                ('reason', models.TextField(help_text='Reason for the deletion request', verbose_name='reason')),
                ('status', models.CharField(choices=[('pending', 'Pending Admin Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='status')),
                ('review_comment', models.TextField(blank=True, default='', verbose_name='review comment')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank_deletion_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_bank_deletion_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'question bank deletion request',
                'verbose_name_plural': 'question bank deletion requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
