# Generated by Django 5.0.6 on 2026-09-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0016_questionbankdeletionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Optional validity expiry for periodic Question Bank review (D1 §4.3). Once past this date, the question is eligible for the periodic review filter (Question Expiry) and can be re-activated or inactivated in bulk.', null=True, verbose_name='expires at'),
        ),
        migrations.AddField(
            model_name='question',
            name='worked_solution',
            field=models.TextField(blank=True, default='', help_text='Model answer / worked-out solution shown to reviewers (and optionally to the candidate in feedback). Plain or lightly-formatted text.', verbose_name='worked-out solution'),
        ),
    ]
