# Generated by Django 5.0.6 on 2026-09-18 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0017_question_expires_at_question_worked_solution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='assigned_reviewer',
            field=models.ForeignKey(blank=True, help_text='Reviewer routed this question for content review (same-domain routing).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_review_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
