# Generated by Django 5.0.6 on 2026-10-02 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0022_rename_1f_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='assigned_psychometrician',
            field=models.ForeignKey(blank=True, help_text='Psychometrician who sent the question back; resubmissions return to them.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_psychometric_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
