# Generated by Django 5.0.6 on 2026-10-02 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_organization_enabled_modules'),
        ('question_bank', '0022_rename_1f_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='owner_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_categories', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='question',
            name='owner_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_questions', to='organizations.organization'),
        ),
    ]
