# Generated by Django 5.0.6 on 2026-07-02 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="name")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("corporate", "Corporate"),
                            ("corp_exclusive", "Corporate Exclusive"),
                            ("channel_partner", "Channel Partner"),
                        ],
                        default="corporate",
                        max_length=50,
                        verbose_name="type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="contact email"),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="contact phone"),
                ),
                ("website", models.URLField(blank=True, verbose_name="website")),
                (
                    "address_line1",
                    models.CharField(blank=True, max_length=255, verbose_name="address line 1"),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=255, verbose_name="address line 2"),
                ),
                ("city", models.CharField(blank=True, max_length=100, verbose_name="city")),
                ("state", models.CharField(blank=True, max_length=100, verbose_name="state")),
                ("country", models.CharField(blank=True, max_length=100, verbose_name="country")),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=20, verbose_name="postal code"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "organization",
                "verbose_name_plural": "organizations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "group",
                "verbose_name_plural": "groups",
                "ordering": ["name"],
                "unique_together": {("organization", "name")},
            },
        ),
        migrations.CreateModel(
            name="OrganizationMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this member is an admin of the organization.",
                        verbose_name="is admin",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members",
                        to="organizations.group",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "organization member",
                "verbose_name_plural": "organization members",
                "ordering": ["-joined_at"],
                "unique_together": {("organization", "user")},
            },
        ),
    ]
