# Generated by Django 5.0.6 on 2026-08-17 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "domain category",
                "verbose_name_plural": "domain categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("assessment", "Assessment"),
                            ("training_course", "Training Course"),
                            ("counseling", "Counseling Service"),
                        ],
                        max_length=20,
                        verbose_name="item type",
                    ),
                ),
                ("item_id", models.PositiveIntegerField(verbose_name="item ID")),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="org_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "organization assignment",
                "verbose_name_plural": "organization assignments",
                "ordering": ["-assigned_at"],
                "unique_together": {("organization", "item_type", "item_id")},
            },
        ),
    ]
