# Generated by Django 5.0.6 on 2026-09-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_domaincategory_organizationassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='region_division',
            field=models.CharField(blank=True, help_text='Region or division of the corporate (CJ_UC052).', max_length=100, verbose_name='region/division'),
        ),
        migrations.AddField(
            model_name='organization',
            name='manager_name',
            field=models.CharField(blank=True, help_text='Name of the primary-contact manager (Doc 9 §2.2).', max_length=255, verbose_name='manager name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tax_id',
            field=models.CharField(blank=True, help_text='PAN/TAN of the organization (Doc 9 §2.2).', max_length=40, verbose_name='PAN/TAN'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='employee ID'),
        ),
    ]
