# Generated by Django 5.0.6 on 2026-09-18 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_psychometricgroupresponse'),
        ('organizations', '0003_group_region_division_organization_manager_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(verbose_name='scheduled at')),
                ('notified', models.BooleanField(default=False, verbose_name='members notified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='assessment.assessment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Optional — schedule for one group only; NULL = whole organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_schedules', to='organizations.group')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_schedules', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'assessment schedule',
                'verbose_name_plural': 'assessment schedules',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='CorporateWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=63, unique=True, verbose_name='slug')),
                ('company_name', models.CharField(max_length=255, verbose_name='company name')),
                ('logo_url', models.CharField(blank=True, max_length=1000, verbose_name='logo URL')),
                ('layout', models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('minimal', 'Minimal')], default='classic', max_length=20, verbose_name='layout')),
                ('primary_color', models.CharField(default='#4f46e5', max_length=9, verbose_name='primary color')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.ForeignKey(blank=True, help_text='The generated corporate-admin account for this website (CJ_UC055).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_websites', to=settings.AUTH_USER_MODEL)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_website', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'corporate website',
                'verbose_name_plural': 'corporate websites',
                'ordering': ['-created_at'],
            },
        ),
    ]
