# Generated by Django 5.0.6 on 2026-10-02 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_assessmentschedule_corporatewebsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent group; empty for a top-level group (Report 9 #23).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organizations.group'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='can_view_member_reports',
            field=models.BooleanField(default=False, help_text="Group Admin only: may view and download his group members' reports.", verbose_name="can view & download members' reports"),
        ),
    ]
