# Generated by Django 5.0.6 on 2026-10-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_assessmentschedule_corporatewebsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatewebsite',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='corporate_logos/', verbose_name='logo'),
        ),
    ]
