# Generated by Django 5.0.6 on 2026-10-02 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_corporatewebsite_logo_upload'),
        ('training', '0011_courseregistration_organization_assigned_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(verbose_name='scheduled at')),
                ('notified', models.BooleanField(default=False, verbose_name='members notified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_schedules', to='training.trainingcourse')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_course_schedules', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Optional — schedule for one group only; NULL = whole organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_schedules', to='organizations.group')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_schedules', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'course schedule',
                'verbose_name_plural': 'course schedules',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
