# Generated by Django 5.0.6 on 2026-10-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_courseschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='enabled_modules',
            field=models.JSONField(blank=True, help_text='Module codes this organization may use; empty means all.', null=True, verbose_name='enabled modules'),
        ),
    ]
