# Generated by Django 5.0.6 on 2026-10-03 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_organization_enabled_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentschedule',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Optional — schedule for one group only; NULL = whole organization.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_schedules', to='organizations.group'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Optional — schedule for one group only; NULL = whole organization.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_schedules', to='organizations.group'),
        ),
    ]
