# Generated by Django 5.0.6 on 2026-10-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_schedule_group_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationassignment',
            name='item_type',
            field=models.CharField(choices=[('assessment', 'Assessment'), ('training_course', 'Training Course'), ('counseling', 'Counseling Service'), ('profiling_solution', 'Profiling Solution')], max_length=20, verbose_name='item type'),
        ),
    ]
