# Generated by Django 5.0.6 on 2026-07-19 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessment", "0002_assessment_assessment_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BandDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        help_text="The variable (section) this band definition applies to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="band_definitions",
                        to="assessment.assessmentsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "band definition",
                "verbose_name_plural": "band definitions",
                "ordering": ["selected_assessment__order", "section__level", "section__order"],
            },
        ),
        migrations.CreateModel(
            name="Band",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "band_number",
                    models.PositiveIntegerField(
                        help_text="1-based index within the definition", verbose_name="band number"
                    ),
                ),
                (
                    "range_min",
                    models.FloatField(
                        default=0,
                        help_text="Lower bound (0-100, inclusive)",
                        verbose_name="range min",
                    ),
                ),
                (
                    "range_max",
                    models.FloatField(
                        default=100,
                        help_text="Upper bound (0-100, inclusive)",
                        verbose_name="range max",
                    ),
                ),
                (
                    "band_code",
                    models.CharField(
                        help_text="Short code (e.g., ANH1, ARM)",
                        max_length=20,
                        verbose_name="band code",
                    ),
                ),
                (
                    "sub_variable_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="For Polar assessments: the sub-variable name for this band.",
                        max_length=100,
                        verbose_name="sub-variable name",
                    ),
                ),
                (
                    "band_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bands",
                        to="career_profiling.banddefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "band",
                "verbose_name_plural": "bands",
                "ordering": ["band_number"],
            },
        ),
        migrations.CreateModel(
            name="ProfilingSolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("purpose", models.TextField(blank=True, verbose_name="purpose")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "image",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Solution image as URL or base64 data URL.",
                        null=True,
                        verbose_name="image",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft (being configured)"),
                            ("published", "Published (available for profiling)"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "has_polar_assessment",
                    models.BooleanField(
                        default=False,
                        help_text="If true, sub-variable band definition is required.",
                        verbose_name="has polar assessment",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profiling_solutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "profiling solution",
                "verbose_name_plural": "profiling solutions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SelectedAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Short name for this assessment in the solution (e.g., CAT, CIA)",
                        max_length=50,
                        verbose_name="label",
                    ),
                ),
                (
                    "is_polar",
                    models.BooleanField(
                        default=False,
                        help_text="If true, this assessment is a Polar-type assessment.",
                        verbose_name="is polar",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiling_solutions",
                        to="assessment.assessment",
                    ),
                ),
                (
                    "solution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_assessments",
                        to="career_profiling.profilingsolution",
                    ),
                ),
            ],
            options={
                "verbose_name": "selected assessment",
                "verbose_name_plural": "selected assessments",
                "ordering": ["order"],
                "unique_together": {("solution", "assessment")},
            },
        ),
        migrations.AddField(
            model_name="banddefinition",
            name="selected_assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="band_definitions",
                to="career_profiling.selectedassessment",
            ),
        ),
        migrations.CreateModel(
            name="MatchIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("career_title", models.CharField(max_length=255, verbose_name="career title")),
                (
                    "variable_mapping_index",
                    models.FloatField(
                        blank=True,
                        help_text="Average mapping score across all variables (0-100)",
                        null=True,
                        verbose_name="variable mapping index (VMI)",
                    ),
                ),
                (
                    "final_match_index",
                    models.FloatField(
                        blank=True,
                        help_text="Final match score (0-100, higher = better match)",
                        null=True,
                        verbose_name="final match index (FMI)",
                    ),
                ),
                (
                    "variable_details",
                    models.JSONField(
                        blank=True,
                        help_text="Per-variable breakdown: band codes, mapping scores, etc.",
                        null=True,
                        verbose_name="variable details",
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_indices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_indices",
                        to="career_profiling.profilingsolution",
                    ),
                ),
            ],
            options={
                "verbose_name": "match index",
                "verbose_name_plural": "match indices",
                "ordering": ["-final_match_index"],
                "unique_together": {("solution", "candidate", "career_title")},
            },
        ),
        migrations.CreateModel(
            name="MappingCriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "career_title",
                    models.CharField(
                        help_text="e.g., 'Computer Programmer'",
                        max_length=255,
                        verbose_name="career title",
                    ),
                ),
                (
                    "criterion_band_code",
                    models.CharField(
                        help_text="The ideal band code for this variable (e.g., 'ANH1')",
                        max_length=20,
                        verbose_name="criterion band code",
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=1.0,
                        help_text="Weight for this variable in the match index (default 1.0)",
                        verbose_name="weight",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        help_text="The variable (section) this criterion applies to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapping_criteria",
                        to="assessment.assessmentsection",
                    ),
                ),
                (
                    "solution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapping_criteria",
                        to="career_profiling.profilingsolution",
                    ),
                ),
            ],
            options={
                "verbose_name": "mapping criterion",
                "verbose_name_plural": "mapping criteria",
                "ordering": ["career_title", "section__level", "section__order"],
                "unique_together": {("solution", "career_title", "section")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="banddefinition",
            unique_together={("selected_assessment", "section")},
        ),
    ]
