# Generated by Django 5.0.6 on 2026-07-20 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_assessment_assessment_type'),
        ('career_profiling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mappingcriterion',
            options={'ordering': ['career_stream', 'career_title', 'section__level', 'section__order'], 'verbose_name': 'mapping criterion', 'verbose_name_plural': 'mapping criteria'},
        ),
        migrations.AlterUniqueTogether(
            name='mappingcriterion',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='matchindex',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mappingcriterion',
            name='career_code',
            field=models.CharField(blank=True, default='', help_text="Short code (e.g., 'ITCP')", max_length=50, verbose_name='career code'),
        ),
        migrations.AddField(
            model_name='mappingcriterion',
            name='career_description',
            field=models.TextField(blank=True, default='', verbose_name='career description'),
        ),
        migrations.AddField(
            model_name='mappingcriterion',
            name='career_stream',
            field=models.CharField(blank=True, default='', help_text="e.g., 'IT Sector' — groups careers in reports.", max_length=255, verbose_name='career stream'),
        ),
        migrations.AddField(
            model_name='mappingcriterion',
            name='rank_order',
            field=models.PositiveIntegerField(blank=True, help_text='Rank order (1..N) into the RankDefinition chart. Leave null when the assessment has no rank system defined.', null=True, verbose_name='rank order'),
        ),
        migrations.AddField(
            model_name='matchindex',
            name='career_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='career code'),
        ),
        migrations.AddField(
            model_name='matchindex',
            name='career_stream',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='career stream'),
        ),
        migrations.AlterField(
            model_name='mappingcriterion',
            name='weight',
            field=models.FloatField(default=1.0, help_text='Weight for this variable in the match index. Used only when rank_order is null (unranked mode). Ignored when a RankDefinition exists for the parent selected_assessment.', verbose_name='weight (legacy / unranked mode)'),
        ),
        migrations.AlterUniqueTogether(
            name='mappingcriterion',
            unique_together={('solution', 'career_stream', 'career_title', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='matchindex',
            unique_together={('solution', 'candidate', 'career_title', 'career_code')},
        ),
        migrations.CreateModel(
            name='RankDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_polar', models.BooleanField(default=False, help_text='If true, rank values are looked up by (match_code, rank_order) via PolarRankValue. If false, by rank_order alone via RankValue.', verbose_name='is polar rank chart')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rank_definition', to='career_profiling.selectedassessment')),
            ],
            options={
                'verbose_name': 'rank definition',
                'verbose_name_plural': 'rank definitions',
            },
        ),
        migrations.CreateModel(
            name='PolarMatchRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion_band_code', models.CharField(help_text="e.g., 'SRC1'", max_length=20, verbose_name='criterion band code')),
                ('user_band_code', models.CharField(help_text="e.g., 'SRC1' or 'SRM'", max_length=20, verbose_name='user band code')),
                ('match_code', models.CharField(choices=[('HM', 'High Match (value 5)'), ('MM', 'Moderate Match (value 3)'), ('LM', 'Low Match (value 1)')], max_length=2, verbose_name='match code')),
                ('match_value', models.PositiveIntegerField(default=5, help_text='Numeric value: HM=5, MM=3, LM=1', verbose_name='match value')),
                ('band_definition', models.ForeignKey(help_text="The polar variable's band definition this rule applies to.", on_delete=django.db.models.deletion.CASCADE, related_name='polar_match_rules', to='career_profiling.banddefinition')),
            ],
            options={
                'verbose_name': 'polar match rule',
                'verbose_name_plural': 'polar match rules',
                'ordering': ['criterion_band_code', 'user_band_code'],
                'unique_together': {('band_definition', 'criterion_band_code', 'user_band_code')},
            },
        ),
        migrations.CreateModel(
            name='PolarRankValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_code', models.CharField(choices=[('HM', 'High Match (value 5)'), ('MM', 'Moderate Match (value 3)'), ('LM', 'Low Match (value 1)')], max_length=2, verbose_name='match code')),
                ('rank_order', models.PositiveIntegerField(verbose_name='rank order')),
                ('rank_value', models.FloatField(verbose_name='rank value')),
                ('rank_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polar_rank_values', to='career_profiling.rankdefinition')),
            ],
            options={
                'verbose_name': 'polar rank value',
                'verbose_name_plural': 'polar rank values',
                'ordering': ['match_code', 'rank_order'],
                'unique_together': {('rank_definition', 'match_code', 'rank_order')},
            },
        ),
        migrations.CreateModel(
            name='RankValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_order', models.PositiveIntegerField(help_text='1-based position in the chart (Rank1, Rank2, ...)', verbose_name='rank order')),
                ('rank_value', models.FloatField(help_text='The weight applied when this rank is selected (e.g., 2.0)', verbose_name='rank value')),
                ('rank_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_values', to='career_profiling.rankdefinition')),
            ],
            options={
                'verbose_name': 'rank value',
                'verbose_name_plural': 'rank values',
                'ordering': ['rank_order'],
                'unique_together': {('rank_definition', 'rank_order')},
            },
        ),
    ]
