# Generated by Django 5.0.6 on 2026-09-11 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_profiling', '0002_rank_system_and_polar'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion_band_code', models.CharField(help_text="e.g., 'ANH2'", max_length=20, verbose_name='criterion band code')),
                ('user_band_code', models.CharField(help_text="e.g., 'ANH1'", max_length=20, verbose_name='user band code')),
                ('value', models.PositiveIntegerField(help_text='Mapping score for this (criterion, user) band combination.', verbose_name='mapping value')),
                ('band_definition', models.ForeignKey(help_text="The standard variable's band definition this rule applies to.", on_delete=django.db.models.deletion.CASCADE, related_name='mapping_rules', to='career_profiling.banddefinition')),
            ],
            options={
                'verbose_name': 'mapping rule',
                'verbose_name_plural': 'mapping rules',
                'ordering': ['criterion_band_code', 'user_band_code'],
                'unique_together': {('band_definition', 'criterion_band_code', 'user_band_code')},
            },
        ),
    ]
