# Generated by Django 5.0.6 on 2026-10-03 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_profiling', '0003_mappingrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilingSolutionModificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_title', models.CharField(blank=True, default='', help_text="Snapshot of the solution's title, kept for the audit trail.", max_length=255, verbose_name='solution title')),
                ('action', models.CharField(choices=[('edit', 'Edit Title'), ('delete', 'Delete Solution')], max_length=10, verbose_name='action')),
                ('proposed_title', models.CharField(blank=True, help_text="New title requested (only for action='edit').", max_length=255, null=True, verbose_name='proposed title')),
                ('reason', models.TextField(help_text='Reason for the edit/delete request', verbose_name='reason')),
                ('status', models.CharField(choices=[('pending', 'Pending Admin Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='status')),
                ('review_comment', models.TextField(blank=True, default='', verbose_name='review comment')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiling_modification_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiling_modification_reviews', to=settings.AUTH_USER_MODEL)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modification_requests', to='career_profiling.profilingsolution')),
            ],
            options={
                'verbose_name': 'profiling solution modification request',
                'verbose_name_plural': 'profiling solution modification requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
